### ISSUE TITLE
Problem with generic type

### ISSUE THREAD

**Issue by kentwinder** [hkellaway/Gloss#109]
So, I have json like this, data inside result sometimes is string, sometimes is an object

```
{
    "status": "success",
    "message": "",
    "result":
    {
        "test_result": "Blah blah blah"
    }
}
```

Here is my code

```
struct Response<T>: Decodable {
    let status: String?
    let message: String?
    let result: T?
    
    init?(json: JSON) {
        self.status = "status" <~~ json
        self.message = "message" <~~ json
        self.result = "result" <~~ json
    }
}
```

```
struct TestResponse: Decodable {
    let testResult: String?
    
    init?(json: JSON) {
        self. testResult = "test_result" <~~ json
    }
}
```

```
Alamofire.request(.GET, url)
    .responseJSON { response in
        if let json = response.result.value as? [String: AnyObject] {
            guard let testObj = Response<TestResponse>(json: json) else {
                print("Error initializing object")
                return
            }
            debugPrint(testObj)
        }
}
```

And the ```result``` is always nil T_T, did I do something wrong here?

**Comment by hkellaway** [comment]
the `result` value in your examples is actually part of the `Alamofire` library, and not Gloss :/

for good measure, i tested just the Gloss portion of what you have there (the models and the initializing with JSON) - and that's just fine

**Comment by kentwinder** [comment]
No, it's the result in Response class, not the result from Alamofire
Here is the log
`Test_Project.Response<Test_Project.TestResponse>(status: Optional("success"), message: nil, result: nil)`

**Comment by hkellaway** [comment]
oh, sorry - i misunderstood; i'll take another look

**Comment by hkellaway** [comment]
in order for the nested model to be translated as expected, you need to indicated it's `Decodable`:

```
struct Response<T: Decodable>: Decodable {
    let status: String?
    let message: String?
    let result: T?
    
    init?(json: JSON) {
        self.status = "status" <~~ json
        self.message = "message" <~~ json
        self.result = "result" <~~ json
    }
}
```

**Comment by kentwinder** [comment]
Oh, works like charm!
Thank you very much, have a good day! ^^
