### ISSUE TITLE
Do not create NSDateFormatter on each decoding/encoding operation

### ISSUE THREAD

**Issue by GUL-** [hkellaway/Gloss#110]
`NSDateFormatter` (and `NSFormatter` in general) costs a lot to create.
In order to improve performance, it is better to keep a single instance of it as a global property.

Furthermore, it could be useful to make public the formatter and related date formats used by Gloss.

**Comment by hkellaway** [comment]
good call. the only `NSDateFormatter` created by the library is for ISO8601 dates - that will be made lazy. for other dates, the client passes in the date formatter, so it's up to them to make sure it's instantiated only once. this update will be available in `0.7.0` - thanks!
