### ISSUE TITLE
modelsFromJSONArray(jsonArray:) should return [Self] instead of [Self]?

### ISSUE THREAD

**Issue by ejmartin504** [hkellaway/Gloss#118]
In the implementation of the method in the extension to Decodable, it will always return an array, even if it's empty:

```swift
static func modelsFromJSONArray(jsonArray: [JSON]) -> [Self]? {
        var models: [Self] = []
        
        for json in jsonArray {
            let model = Self(json: json)
            if let model = model {
                models.append(model)
            }
        }
        
        return models
    }
```

I bring this up only because I've run into a lot of annoying places where I am forced to either "if let
 or force unwrap when working with JSON arrays.

Happy to PR it if you agree with the change.

**Comment by hkellaway** [comment]
how `modelsFromJSONArray` is implemented is changed slightly in upcoming `0.7.0`release - so i'll revisit the request there. i'll leave this open until that release

**Comment by ejmartin504** [comment]
Looks to be no longer an issue on the current development branch.

**Comment by ejmartin504** [comment]
Whoops, realize you wanted it to be open before your release -- my bad :-)

**Comment by hkellaway** [comment]
0.7.0 has been release :tada: should not longer be experiencing this issue
