### ISSUE TITLE
Missing file in 0.7.0

### ISSUE THREAD

**Issue by nmodin** [hkellaway/Gloss#122]
Seems like there is a a missing file (Dictionary.swift), or that this should be removed from the build ?

```
*** Fetching Gloss
*** Checking out Gloss at "0.7.0"
*** xcodebuild output can be found in /var/folders/qj/_6jn0qb931n9f5t_xg5d52pw0000gn/T/carthage-xcodebuild.xJJzcc.log
*** Building scheme "Gloss" in Gloss.xcodeproj
** BUILD FAILED **


The following build commands failed:
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(1 failure)
<unknown>:0: error: no such file or directory: '/Users/nmodin/dev/github/ScoreCard/Carthage/Checkouts/Gloss/Sources/Dictionary.swift'
A shell task failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(1 failure)
```

**Comment by hkellaway** [comment]
that file was renamed in the latest version. can you try clearing whatever you have downloaded and doing a clean install?

**Comment by nmodin** [comment]
So I downloaded a new clean zip copy and opened the project into xcode and it seems to still think this file should be there. The "Dictionary.swift" is marked red and the build fails with :

```
<unknown>:0: error: no such file or directory: '/Users/nmodin/Downloads/Gloss-develop/Sources/Dictionary.swift'
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1
```

Removing the reference to Dictionary gives an error as expected, and then adding ExtensionArray and ExtensionDictionary to the project fixes the issue. 

Perhaps the xcode project file changes wasn't committed for some odd reason ?

**Comment by hkellaway** [comment]
I'll give that a try

**Comment by hkellaway** [comment]
@nmodin you're totally right - thanks for catching that! can i bother you to try using the version at the branch `bugfix/carthage_missing_dictionary ` and verifying that works as expected?

**Comment by nmodin** [comment]
Boom ! Worked like clockwork. Now I'll get back to the tutorial ....  thanks for a speedy fix ! :)

**Comment by hkellaway** [comment]
no prob - will be releasing a new version shortly. thanks for the help
