### ISSUE TITLE
Runtime check of Decodable/Encodable when using gloss models in Generics 

### ISSUE THREAD

**Issue by RahulKatariya** [hkellaway/Gloss#127]
Suppose I have a Generic Response Class like below

``` swift
import Gloss

struct GenericResponse<T>: Glossy {

    var errorMessage: String?
    var status: Bool?
    var data: T

    init?(json: JSON) { 
        guard let data: T = "data" <~~ json else { return nil } 

        self.errorMessage =  "errorMessage" <~~ json
        self.status =  "status" <~~ json ?? false
        self.data = data
    }

    func toJSON() -> JSON? {
        return jsonify([ 
            "errorMessage" ~~> self.errorMessage,
            "status" ~~> self.status,
            "data" ~~> self.data
        ])
    }

}
```

And two JSON objects 
1. `["errorMessage": nil, status: true, data: "Some text goes here which is of type string and doesn't conform to Glossy"]`
2.  `["errorMessage": nil, status: true, data: ["name":"This is a model which conforms to Glossy Protocol"]]`

Now when I try to init the Generic Response method with 2nd JSON Object, It returns me nil as it calls the func Decoder.decode() -> JSON -> T?. To solve this issue I have to make my Generic in GenericResponse model conform to Glossy Protocol like `struct GenericResponse<T: Glossy>: Glossy` but then it gives error with the 1st JSON Object because the data is of type string and it doesn't conform to Glossy.

I was able to solve the problem at the time of encoding.

I created a Protocol

``` swift
struct AnyEncodable: Encodable {

    let value: Encodable

    func toJSON() -> JSON? {
        return value.toJSON()
    }

}
```

and then tweak the function Encode

``` swift
public static func encode<T>(key: String) -> T? -> JSON? {
    return {
        property in

        if let property = property as? Encodable {
            return encodeEncodable(key)(AnyEncodable(value: property))
        } else if let property = property as? AnyObject {
            return [key : property]
        }

        return nil
    }
}
```

Reference:
http://stackoverflow.com/questions/35431712/generic-method-override-not-working-in-swift/35434838?noredirect=1#comment58569896_35434838

Is there any way i can work around this problem at the time of Decoding ?

**Comment by hkellaway** [comment]
im going to have to look into this on the weekend; no answer springs out at me immediately.
