### ISSUE TITLE
"Consecutive statements on a line" when using <~~ operator

### ISSUE THREAD

**Issue by johngoren** [hkellaway/Gloss#134]
This software is rad and is saving my bacon, but for some reason it seems picky about spaces in using the <~~ operator...

If I do it like this it throws the above error.

self.id = "_id" <~~json

But if I get rid of all spaces it works without a hitch:

self.id = "_id"<~~json

But then the moment I put a space back in on one side, the "consecutive statements" complaint is back:

self.id = "_id"<~~ json

One space on each side, though, and it works fine. It took me a while to figure this out...

**Comment by johngoren** [comment]
Just realized that all math operators act like this too. Anyway just thought this one might be extra-prone to spacing confusion for folks...thanks again.

**Comment by hkellaway** [comment]
:+1:
