### ISSUE TITLE
NSManagedObject and Gloss interaction?

### ISSUE THREAD

**Issue by cody1024d** [hkellaway/Gloss#137]
I've been researching possible JSON mapping libraries, and have been trying to come up with a solution that will allow me to map the JSON into CoreData models.  I have seen several object mapping libraries that struggle when hydrating a CoreData model (implements the NSManagedObject protocol) through the library

Is this something that Gloss allows?

**Comment by hkellaway** [comment]
Gloss does not currently have any features related to CoreData and support isn't currently intended. Good luck with the search!

**Comment by cody1024d** [comment]
ahh shucks, haha.  Either way, thank you for the quick response!
