### ISSUE TITLE
Disappearing field when encoding dictionary

### ISSUE THREAD

**Issue by MatthiasLamoureux** [hkellaway/Gloss#139]
Hello, 
I encounter a strange problem. Being new to Gloss, I may be using it the wrong way, but I'm puzzled by the way it works, so I wondered if it could be an issue.

Let's assume we have an encodable struct:

    struct testStruct : Encodable {
        let attrib : String
        func toJSON() -> JSON? {
            return jsonify([
                "type" ~~> "TEST",
                "attrib" ~~> attrib
                ])
        }
    }

The resulting json being an object containing two fields `type` and `attrib`.

Now let's create a dictionary of structs:

    let dict = [
        "a":testStruct(attrib:"First"),
        "b":testStruct(attrib:"Second")
    ]

Finally I `jsonify` my final object with that code:

    jsonify([
        "field" ~~> "Hello",
        "disapearingField" ~~> dict
    ])

Here what I get:

    {
        "field": Hello, 
        "b": {
            attrib = Second
            type = TEST
        }, 
        "a": {
            attrib = First
            type = TEST
        }
    }

I was expecting something like that:

    {
        "field": Hello, 
        "disapearingField": {
            "b": {
                attrib = Second
                type = TEST
            }, 
            "a": {
                attrib = First
                type = TEST
            }
        }
    }
 
So is that a functionality and I do not use Gloss the way it should be, or is that a bug?

Thanks in advance

**Comment by hkellaway** [comment]
apologies for the late response, couldn't dig into this until the weekend.

to achieve the desired effect, your model should look as such:

```
struct testStruct : Decodable, Encodable {
    
    let attrib : String
    
    init?(json: JSON) {
        guard let attrib: String = "attrib" <~~ json else {
            return nil
        }
        
        self.attrib = attrib
    }
    
    init(attrib: String) {
        self.attrib = attrib
    }
    
    func toJSON() -> JSON? {
        return jsonify([
            "type" ~~> "TEST",
            "attrib" ~~> attrib
            ])
    }
}
```

notice the additions - the model is now declared as `Decodable` and the required `init?(json:)` is defined. 

i have to think through what the expected outcome of providing a dictionary with `Encodable` values without providing `Decodable` information should be. however, this should achieve your intention. hope that helps!
