### ISSUE TITLE
fromJSONArray

### ISSUE THREAD

**Issue by whvandervelde** [hkellaway/Gloss#143]
Hi,

From the examples.
Something like below will give compiler errors for Swift 2.2, because fromJSONArray returns [RepoOwner] and not an optional. So checking for something going wrong here doesn't seem to work?

```
guard let repoOwners = [RepoOwner].fromJSONArray(repoOwnersJSON)
    else { /* handle nil array here */ }
```

I think it makes sense to add throws for fromJSONArray in case of errors. From what I understand for example Freddy does something like this and I think something similar help make this safer?

**Comment by hkellaway** [comment]
`fromJSONArray` will always return an array, not an Optional array - it will be an array of _any values that were parsed_.

if at the application level something is wrong - for example, you're expecting the `repoOwners` array to equal the number of objects in the JSON array else the application should cease execution - your application could include the following: 

```
let repoOwners = [RepoOwner].fromJSONArray(repoOwnersJSON)

guard repoOwners.count == repoOwnersJSON.count else {
    fatalError("Cease execution")
}
```

hope that helps!

**Comment by whvandervelde** [comment]
Thanks, yes I did something similar like this indeed. 
It can detect if something went wrong, but perhaps not what went wrong exactly?
In any case, the example  in the doc might need a small update then.
Thanks again!

**Comment by hkellaway** [comment]
good call - thanks!
