### ISSUE TITLE
Int32 type of var cannot be parsed using Gloss

### ISSUE THREAD

**Issue by mihirpmehta** [hkellaway/Gloss#151]
I have a class variable which i need to take as Int32 and not Int 

`var systemType: Int32`

when ever i try to parse this using 

self.systemType = ("SystemType" <~~ dictionary)!

app crashed saying **fatal error: unexpectedly found nil while unwrapping an Optional value**

i can avoid the crash by `if let` but it will not parse the value.

**Comment by hkellaway** [comment]
`Int32` is not one of the types handled automatically (https://github.com/hkellaway/Gloss#on-using-gloss-operators). you can create your own custom decoding function (https://github.com/hkellaway/Gloss#custom-transformations); you might extend `Decoder` something like as follows:

```
extension Decoder {
    
    static func decodeInt32(key: String, json: JSON) -> Int32? {
        if let number = json.valueForKeyPath(key) as? NSNumber {
            return number.intValue
        }
        
        return nil
    }
    
}
```

hope the helps!

**Comment by hkellaway** [comment]
Release `0.7.3` adds decoding for `Int32` 🎉
