### ISSUE TITLE
json integer not decoded as Int

### ISSUE THREAD

**Issue by psparago** [hkellaway/Gloss#155]
I'm 99% certain this is not a Gloss issue, but I thought I'd ask the question here to see if anyone else has experienced this with Swift/JSON.

I am calling a Flickr API which returns the following JSON (snippet): 

(Please note that the snippet is the output from a print of a JSON object (map) which is defined [String:AnyObject]). 

`{
    person =     {
        "can_buy_pro" = 0;
        description =         {
            "_content" = "";
        };
        "has_stats" = 0;
        iconfarm = 2;
        iconserver = 1523;
...
}
`

Note the two fields: 'iconfarm' and 'iconserver'. They are clearly JSON integers.

When I used the following Gloss code:

`
        guard let iconServer: Int = "person.iconserver" <~~ json,
            let iconFarm: Int = "person.iconfarm" <~~ json
            else { return FlickrDefaultBuddyIconUrl }
`

iconFarm was correctly converted to the integer 2 and iconServer was nil.

When looking at the Gloss code, I found it ultimately boiled down to code such as the following:

`
           if let iconserver = person["iconserver"] {
                  let x = iconserver as? Int
                   print("x: \(x)")
            }
`
When I looked more closely, I find iconserver is of type NSString, but iconfarm is NSNumber.

I added the following:
`
                                let y = Int((iconserver as? String)!)
`
which correctly converts the iconserver NSString to an Integer.

Is this a Swift issue?

Has anyone experienced anything like this? Could there be something in the JSON string on the wire that confuses the JSON parse? If so, what's the best way to get the raw NSData returned by the NSURLRequest in printable form?

Note: I'm using OAuthSwift as my network request library.

**Comment by hkellaway** [comment]
hm, not sure what's going on just yet. can you try something? model the number as an Int33 and use the branch 'release/0.7.3' - that has decoding added for detecting NSNumbers and converting them to Int32 (or Int64)

**Comment by psparago** [comment]
Thank you so much for the quick response and interest Harlan. Especially since it seems unlikely like it is a Gloss issue. By the way, I really like Gloss. Thank you for your contribution!!

I will do this.

**Comment by psparago** [comment]
I updated my podfile like this:

pod 'Gloss', :git=>'https://github.com/hkellaway/Gloss', :branch=>'release/0.7.3'

and added this test code:
`
                        if let iconServer: Int32 = "person.iconserver" <~~ json {
                            print("iconserver: \(iconServer)")
                        } else {
                            print("no good")
                        }

`
Unfortunately, iconServer is still nil.

Thank you again for your interest.

**Comment by hkellaway** [comment]
I'll look more closely when I have the chance. If nothing else you can make your own tranformation (https://github.com/hkellaway/Gloss#custom-transformstions) using the code you mentioned to transform into an Int

**Comment by hkellaway** [comment]
sorry hadn't got the chance to think through this until today. if the type is coming through as an `NSString` but you want it to be an `Int`, I should have suggested a custom transformation originally. you could use something like this:

```
extension Decoder {
    
    static func decodeStringToInt(key: String, json: JSON) -> Int? {
        if let string = json.valueForKeyPath(key) as? String {
            return Int(string)
        }
        
        return nil
    }
    
}
```

and that would be called as such: `let iconserver: Int = Decoder.decodeStringToInt("person.iconserver", json: json)`

hope that works for you

**Comment by psparago** [comment]
Thank you Harlan. That code works well. I'm still baffled regarding why the JSONSerializer returns both String and Int types for integers seemingly randomly.
