### ISSUE TITLE
How to pass the Decodable type variable

### ISSUE THREAD

**Issue by x4080** [hkellaway/Gloss#159]
Hi I decode JSON into class A (decode in the function in class), just say A.customers, and when I print the content of this object it works fine

The problem is when I am at the viewcontroller, I cannot print that same object, the error is
```
fatal error: unexpectedly found nil while unwrapping an Optional value
```

PS : the source which is type of JSON, is passable to the viewcontroller btw

Am I doing it wrongly?

**Comment by hkellaway** [comment]
the initializer is failable - you must use 'guard' or 'if let' to make sure the model is instantiated at runtime (https://github.com/hkellaway/Gloss#initializing-model-objects-and-arrays).

the fact that you're coming out with that error means decoding is failing for some reason - perhaps the setup in your model is not quite right
