### ISSUE TITLE
Array of mixed types

### ISSUE THREAD

**Issue by markovaljaots** [hkellaway/Gloss#160]
Is it possible to parse arrays that contain mixed types? 

For example in my JSON I have this array:

```json
"actiontasklist": [
  { "actiontype": "play_sound", "id": "VO1" },
  "INTERACTION_BLOCK"
]
```
What would be the best solution to parse this array or what would be my options?

**Comment by hkellaway** [comment]
you'll want to get creative with your own transformation (https://github.com/hkellaway/Gloss#custom-transformations). #113 is an example.
