### ISSUE TITLE
ContainObjects function unclear

### ISSUE THREAD

**Issue by jose920405** [hkellaway/Gloss#164]
Exist a equivalent for this function in objects type glossy.

if found 
`contains(<#T##predicate: (object) throws -> Bool##(object) throws -> Bool#>)`

But i don't understand how works.

Can help me?

**Comment by hkellaway** [comment]
i'm not really sure what you're asking here. can you provide sample code or pseudocode of what you're attempting?

**Comment by jose920405** [comment]
I have 2 arrays type Glossy
```
var locations: [Location] = [Location]()
var filterLocations: [Location] = [Location]()
```

in a loop a need know if any object inside `locations` exist in `filterLocations`

example:
```
for loc in locations {
   if filterLocations.contains(loc) {
      ///Here contain
   }
}
````

**Comment by hkellaway** [comment]
i see. that's more of a coding question not specific to Gloss so I'm not going to go too in depth. 

off the top of my head, without giving it a try - it may be that you just need to implement the `Equatable` protocol for your `Location` model.
