### ISSUE TITLE
How to decode JSON dictionaries with variable/unknown keys

### ISSUE THREAD

**Issue by Framnk** [hkellaway/Gloss#179]
Is there a way to use Gloss to decode JSON with keys that are unknown in advance?  For instance:

{ "key_1234": {
     <some model>
  },
  "key_4567": {
    <some model>
  }
}

**Comment by hkellaway** [comment]
Theres nothing in the library specific to this scenario. Perhaps, create a custom transformation (https://github.com/hkellaway/Gloss#custom-transformations) - in the function you use, you can figure out all the key names based on the number of keys in the dictionary, and transform them how you want. That assumes the pattern for what the keys are is consistent and known.

Hope that helps!
