### ISSUE TITLE
Parse parent objects

### ISSUE THREAD

**Issue by AndrewSB** [hkellaway/Gloss#182]
Hey, I was wondering if it was possible to parse a parent object, the inverse of a nested child.

For example, if I have the model Person:

```swift
struct Person {
    let user: User
}
```

Which acted as a wrapper for another model (`User` in this case), defined as so:

```swift 
struct User {
    let id: String
    let name: String
}
```

Can I parse the Person like this:

```swift
extension Person {
    init?(json: JSON) {
        self.user = "" <~~ json
    }
}
```

Where passing an empty string instructs the parser to attempt to parse the entire JSON object?

**Comment by hkellaway** [comment]
not sure i fully get your question here.

in the scenario you provide, there isn't enough information to determine how to "parse the entire JSON" object. 

typically,you'd either want to extend `User` to be `Decodable` as well - and provide the key for the User JSON (not just a blank string).

or, if you're attempting to avoid making `User` a `Decodable` object, as in your code snippets - make your own decoding function:

```
extension Person: Decodable {
    
    init?(json: JSON) {
        guard let user: User = "user" <~~ json else {
            return nil
        }
        
        self.user = user
    }
}

func <~~ (key: String, json: JSON) -> User? {
    return Decoder.decodeUser(key, json: json)
}

extension Decoder {
    
    static func decodeUser(key: String, json: JSON) -> User? {
        guard
            let id = json["id"] as? String,
            let name = json["name"] as? String else {
            return nil
        }
        
        return User(id: id, name: name)
    }
    
}```

**Comment by AndrewSB** [comment]
I was unclear, sorry @hkellaway.
I realized what I want is easily fixed by initializing a User inside Person's initializer.

Thank you!
