### ISSUE TITLE
Decode decimal numbers

### ISSUE THREAD

**Issue by sssilver** [hkellaway/Gloss#183]
Hello,

I have the following JSON:

```swift
let response: JSON = [
    "balance": 123.45,
    "lastUpdated": "2000-01-02T12:34:56.789Z",
    "balanceStale": false
]
```

Unfortunately, when trying to parse it using `<~~`, `balance` comes back as `nil`, even though it's a perfectly valid JSON number type.

What's the workaround?

Thanks.

**Comment by anazareth-rmn** [comment]
What is the destination number type?

**Comment by sssilver** [comment]
```swift
import Gloss


class GFCBalance: Decodable {
    let balance: NSDecimalNumber?
    let lastUpdated: NSDate?
    let balanceStale: Bool?


    required init?(json: JSON) {
        self.balance = "balance" <~~ json
        self.lastUpdated = Decoder.decodeDateISO8601("lastUpdated")(json)
        self.balanceStale = "balanceStale" <~~ json
    }
}

**Comment by hkellaway** [comment]
Gloss does not automatically handle the `NSDecimalNumber` type (handled types: https://github.com/hkellaway/Gloss#on-using-gloss-operators). you should consider a custom transformation (https://github.com/hkellaway/Gloss#custom-transformations)
