### ISSUE TITLE
Test JSON Structure

### ISSUE THREAD

**Issue by YMonnier** [hkellaway/Gloss#184]
Hello,

I would like to know how to test a JSON structure before to map JSON to Object using Gloss?
For example, map JSON to Object if the structure has 3 keys called "name", "age", "birthday", etc..

Are there any good ways to do this?

Thank you,

**Comment by hkellaway** [comment]
not entirely sure what you're asking. if you mean you'd like to verify that the `name`, `age`, etc. are available - thats what you'd use a `guard` statement for:

```
import Gloss

struct MyModel: Decodable {

    let name: String
    let age: Int
    
    init?(json: JSON) {
        guard 
            let name: String = "name" <~~ json,
            let age: Int = "age" <~~ json else {
                return nil
        }

        self.name = name
        self.age = age
    }

}
```

if you're asking about how to write tests for your models, you can have a look at the tests in the `GlossTests` folder of the project https://github.com/hkellaway/Gloss/tree/master/GlossTests
