### ISSUE TITLE
Introduce throwing non-optional decoding operators

### ISSUE THREAD

**Issue by marcopompei** [hkellaway/Gloss#187]
Hello and thanks for the library, I really enjoying using it.

A very common use case is when you need an object with non-optional properties:

``` Swift
guard let
    id: Int = "id" <~~ json,
    name: String = "name" <~~ json
else {
    return nil
}

self.id = id
self.name = name
```

I suggest adding throwing non-optional operators so that same use case can be done using error handling.

Let's say we pick `<~~~` as operator, that same code above could be done in a way less awkward way:

``` Swift
do {
    self.id = try "id" <~~~ json
    self.name = try "name" <~~~ json
} catch {
    return nil
}
```

I'm not sure if `<~~~` would be a good operator name but I do think this idea could be very useful.

I have [an example implementation](https://github.com/marcopompei/Gloss/commit/bfe03bb94d1d97fabc372e4b95254334a4b10abd) and I'm open to do it properly if you guys think it is a good idea.

**Comment by hkellaway** [comment]
thanks for the idea! im gonna think about/play with this a bit.

**Comment by hkellaway** [comment]
@marcopompei gave this a try! i don't see a reason not to have this option. however, i don't have the bandwidth now to implement. 

if you're interested in doing so - i'd be happy to see a PR. it'd need to have implementations for all the existing convenience functions for Decoding and Encoding, tests for all the new operators and their underlying functions, as well as an update to documentation. i'm not well-versed at naming operators either - but i think that one may be confusingly close to the other - so let's say `<~~*` would be acceptable. 

let me know if you're game.

**Comment by marcopompei** [comment]
I'll try to implement it during this week.

**Comment by GoldenJoe** [comment]
What ever happened with this? It would be very helpful.

**Comment by hkellaway** [comment]
cleaning up old issues - if this is still of interest to folks, please submit an implementation along with tests. if not done so in a decent amount of time, i will close

myself, i'll not be investing in this implementation as i support Gloss in maintenance & suggest generally to use Codable
