### ISSUE TITLE
Array Decoding Semantics

### ISSUE THREAD

**Issue by htinlinn** [hkellaway/Gloss#189]
The current default behavior of the decoder when decoding arrays is to return an empty array even if it couldn't decode individual elements. The only requirement there is that the key must exist. 

Updating these functions to return nil instead would make them more consistent with how the rest of the decoder functions behave. Caller gets a value back if the JSON can be decoded and nil otherwise.

**Comment by hkellaway** [comment]
suggested changes have been merged into `develop`. 

because this represents an API change, this won't come out until `0.8.0` is released - which may not be for some months. until then, have your project point to `develop` or commit `39bf67ba74141951a42946716a08cc7e1019e626` to be more specific.

**Comment by htinlinn** [comment]
Changes made seem to cover only one of the many array decoding functions. `decodeDecodableArray`, `decodeEnumArray`, etc...  needs updating as well.

**Comment by hkellaway** [comment]
ah! i only covered `fromJSONArray` and `toJSONArray`. will update

**Comment by hkellaway** [comment]
updated. you can point toward `develop` for the latest, or commit `7868347e2fc93487d1a9d2cb4621a88b247986e4` to be more specific
