### ISSUE TITLE
Better handling of JSON primitives with protocols

### ISSUE THREAD

**Issue by gerbiljames** [hkellaway/Gloss#190]
First off let me say: awesome library! I only came accross this two days ago and I'm already using it in two projects.

I had a look through the issues to see where I could help out and that led me down a rabbit hole in which I think I've found a better way to handle JSON primitives internally using protocols.

Currently, values that can be directly mapped to JSON are handled by 'catch all' encode and decode functions which return generic type `T?`. A problem with this is that the compiler will accept any type for these functions since the generic type is not constrained. This may lead people to accidentally attempt to encode or decode a type which can never be encoded or decoded and they'll get no error from the compiler if they do.

I think that a solution to this is adding two new protocols the first of which is:

``` swift
public protocol JSONPrimitive {}

extension JSONPrimitive {
  public static func decode(key: String, keyPathDelimiter: String = GlossKeyPathDelimiter) -> JSON -> Self? {
    return { json in
      if let value = json.valueForKeyPath(key, withDelimiter: keyPathDelimiter) as? Self {
        return value
      }
      return nil
    }
  }

  public static func encode(key: String) -> Self? -> JSON? {
    return { property in
      if let property = property as? AnyObject {
        return [key : property]
      }
      return nil
    }
  }
}
```

Defining this protocol then means that the encode and decode global functions and operators can be defined like this:

``` swift
public func decode<T: JSONPrimitive>(key: String) -> JSON -> T? {
  return T.decode(key)
}

public func encode<T: JSONPrimitive>(key: String) -> T? -> JSON? {
  return T.encode(key)
}

public func <~~ <T: JSONPrimitive>(key: String, json: JSON) -> T? {
  return decode(key)(json)
}

public func ~~> <T: JSONPrimitive>(key: String, property: T?) -> JSON? {
  return encode(key)(property)
}
```

Then its as easy as:

``` swift
extension String: JSONPrimitive {}
```

to make a type a JSON primitive.

For types that need to be converted when theyre transcoded there is:

``` swift
public protocol JSONPrimitiveConvertible: JSONPrimitive {
  static func decodeItem(json: AnyObject) -> Self?
  func encodeItem() -> AnyObject
}

public extension JSONPrimitiveConvertible {
  static func decode(key: String, keyPathDelimiter: String = GlossKeyPathDelimiter) -> JSON -> Self? {
    return { json in
      if let value = json.valueForKeyPath(key, withDelimiter: keyPathDelimiter) {
        return decodeItem(value)
      }
      return nil
    }
  }

  static func encode(key: String) -> Self? -> JSON? {
    return { property in
      if let property = property {
        return [key: property.encodeItem()]
      }
      return nil
    }
  }
}
```

This protocol significantly reduces the boilerplate in the library since it removes all of the functions and operators for types which need to be converted when theyre transcoded.  To make a type a JSON primitive convertible its as easy as:

``` swift
extension UInt32: JSONPrimitiveConvertible {
  public static func decodeItem(json: AnyObject) -> UInt32? {
    if let number = json as? NSNumber {
      return number.unsignedIntValue
    }
    return nil
  }

  public func encodeItem() -> AnyObject {
    return NSNumber(unsignedInt: self)
  }
}
```

The best part: you get the operators and global functions from `JSONPrimitive` for free!

Theres more work to be done including functions and operators for primitive arrays and tests but I wanted to create this issue first since these are some fairly major changes. I'm happy to submit a PR for this if its something that you would want.

Thanks for reading!

**Comment by hkellaway** [comment]
wow I really appreciate the thoughtwork here! cool stuff. 

this is a vast change - I'll need some time to try it out think about the ramifications. I'll reply back here with my thoughts

**Comment by hkellaway** [comment]
cleaning up old issues - i'll not be investing in this implementation as i support Gloss in maintenance & suggest generally to use Codable
