### ISSUE TITLE
Json Object to JsonArray data 

### ISSUE THREAD

**Issue by ayazahmadtarar** [hkellaway/Gloss#198]
In tutorial only simple JSon array [ [data,data ],[data,data ] ]are mentioned the program works fine for that but whenever i try to get json data from from api it return be json object just like

`{
  "stations" : [
    {
      "stationName" : "Wittenbergplatz",
      "buildYear" : "1912"
    },
    {
      "stationName" : "Spichernstrasse",
      "buildYear" : "1959"
    },
    {
      "stationName" : "Weberwiese",
      "buildYear" : "1930"
    }
  ]
}`

but whenever i try to user function                         
 `                        let subways = [Subway].fromJSONArray(json["stations"])
`
it gives me error unable to cast object,the question is how to convert the JSONobject to JSONoarray so that gloss function can be executed

**Comment by hkellaway** [comment]
not sure i understand completely. to get the `subways` objects, you can do:

```
guard let subways = [Subway].fromJSONArray(json["stations"]) else {
        // handle parsing failure here
}

print(subways)
```
