### ISSUE TITLE
XCode 8 Beta 6 Code Update

### ISSUE THREAD

**Issue by Spriter** [hkellaway/Gloss#202]
Gloss needs an update to run with the XCode 8 Beta 6 swift3 toolchain.

Best regards
Marcel

**Comment by marianoprettysimple** [comment]
Hey, I think you just need to change JSON definition to

`public typealias JSON = [String : Any]`

and ExtensionDictionary.swift line 149 to

`print("[Gloss] Unable to set value: \(subdict) to dictionary of type: \(type(of: self))")`

I made those changes and the Gloss pod project seems to be building now. I'm still trying to figure out all the stuff that broke on my own project, so I can't report if there are any runtime problems.

**Comment by pascalfribi** [comment]
Hi guys,

I was just about to create a pull request for the same changes :-) Now I can throw them away. Nevermind, they look (almost) the same, apart from naming variables.

**Comment by hkellaway** [comment]
@pascalfribi i appreciate the effort regardless
