### ISSUE TITLE
Is it possible to model this? (Question)

### ISSUE THREAD

**Issue by ThoseGuysInTown** [hkellaway/Gloss#203]
I've been looking through the documentation and S.O. but haven't seen anyone post about a JSON data structure like the one I'm trying to model (an array of JSON objects): 

```
{
events: [
        {
          //event: A JSON object I already have a modal for. 
        },
        ... 
    ]
}
```

How I thought it's supposed to be done (it keeps returning nil though):

```
public struct Events: Decodable {
    
    var events: [EventObject]?  // This is the Object I model off of the "event" in the json above
    
    public init(json: JSON) {
        
        self.events = "events" <~~ json
        
    }
    
}
```

**Comment by pascalfribi** [comment]
Hi,

yes of course this is possible. Gloss is really neat.

But your example has a few issues. First of all you need to implement a failable initializer as the decoding could go wrong. Furthermore it seems, that you JSON is not really correct.

With your example you need something like this (Note that events in the json needs to have "" around it):
{
"events": [
        {
          //event: A JSON object I already have a modal for. 
        },
        ... 
    ]
}

public struct Events: Decodable {

    public let events: [EventObject]

    public init?(json: JSON) {

        // First make sure you can decode EventObject
        guard let events: [EventObject] = "events" <~~ json
            else { print("Error decoding EventObject Array"); return nil }

        // Now assign local events to self.events
        self.events = events
    }

}

public struct EventObject {
// Your EventObject struct with failable initializer....

}

**Comment by hkellaway** [comment]
thanks @pascalfribi for helping out! hope that helps
