### ISSUE TITLE
What library/technique would you use to save Glossy objects to file

### ISSUE THREAD

**Issue by sbaker7** [hkellaway/Gloss#205]
Hi,

Not really an issue, more just a general question; what would you recommend to use to save Glossy objects to file? Have you done much work with this before? Have you got any favourites?

Investigating a few ways to do it at the moment and thought you may have some opinions with your more extensive knowledge of the library. Loving it by the way! It is making my life so much easier.

Thanks!

**Comment by hkellaway** [comment]
i've not actually saved Glossy objects to file, so i can't speak to it. i would love if you had thoughts from your experimentation to see them posted back here.

glad you like the library 😄
