### ISSUE TITLE
Decoding a Single Value or Array

### ISSUE THREAD

**Issue by DavidWaldock** [hkellaway/Gloss#206]
I'm relatively new to Swift (many years of C#), but I'm implementing an API and using Gloss as the to deserialise it. The JSON in the model allows the following:

```
  "metadata": [
    {"label":"Editor", "value":"Ed Itor"},
    {"label":"Author": "value":[
        {"@value":"Anne Author"},
        {"@value":"A N Other"}
      ]
    },
    {"label":"Published", "value": [
        {"@value": "Paris, circa 1400", "@language":"en"},
        {"@value": "Paris, environ 1400", "@language":"fr"}
      ]
    },
    {"label":"Source",
     "value": "<span>From: <a href=\"http://example.org/db/1.html\">Some Collection</a></span>",
     "@language":"en"}
  ]
```

As you can see, the value field can be a single string value or an array of values (which sometimes have additional language discriminator).

I've modelled it so that the key(label) and value/language elements are separate (MetadataKey and MetadataValue respectively), with the key having a collection of values. How can I identify if the value is a string (as in Editor or Source) and translate that into a MetadataValue, or just decode an array of MetadataValue items?

**Comment by hkellaway** [comment]
that's not a sort of thing built into Gloss - so you'll want to create your own decoding function (https://github.com/hkellaway/Gloss#custom-transformations).

i don't know exactly your JSON situation, so i'd think on a couple things. if you know that the metadata will always have certain structures like `Editor` and `Source` and that `Editor` and `Source` structures will always have 1 value - perhaps make them their own models. if this is really a random assortment of things that can have any number of values - perhaps model the Values as always an array, and some will simply have only 1 entry.

hope that gives you some ideas!
