### ISSUE TITLE
Change JSON typealias to [String: Any] for Swift 3

### ISSUE THREAD

**Issue by gerbiljames** [hkellaway/Gloss#212]
It seems that Apple are moving away from the use of `AnyObject` in Swift, I've checked and both Alamofire and Moya have followed suit.

I would have submitted a PR but I'm not sure which branch to submit it against.

**Comment by hkellaway** [comment]
i was actually just thinking that myself - was going to work on it tonight. good call!

**Comment by hkellaway** [comment]
included in version `1.0.0` 🎉
