### ISSUE TITLE
There is no spec file in CocoaPods/Specs for Gloss 0.8.0

### ISSUE THREAD

**Issue by wangguangfeng** [hkellaway/Gloss#213]
when i use the pod update for Gloss 0.8.0, but fail. when i use pod search Gloss, i found there is no spec file for Gloss 0.8.0 in https://github.com/CocoaPods/Specs

**Comment by hkellaway** [comment]
I'm having issues pushing to CocoaPods currently. The most current version on CocoaPods would be 0.7.4

**Comment by hkellaway** [comment]
`0.8.0`was actually just pushed

**Comment by wangguangfeng** [comment]
OK, the most current version on CocoaPods is 1.0.0

**Comment by hkellaway** [comment]
yep, released 0.8.0 and 1.0.0 this morning. Swift 2.3 and Swift 3.0 respectively
