### ISSUE TITLE
Array decoding partial success?

### ISSUE THREAD

**Issue by ryanschneider** [hkellaway/Gloss#221]
Previously with 0.7.x, I could decode an array and get back all the items that passed decoding.

For example, if I had the JSON:

```json
{ "values": [ { "value": 4 }, { "value": null }  ] }
```

And wanted to decode that into a struct like so:

```swift
struct Item : Glossy {
   let value: Int
}

func decode(json: JSON) -> [Item] {
    return "values" <~~ json
}
```

That would return `[ { value: 4 } ]`.  With 1.0, it returns `nil`, because of this change to `decode(decodableArrayForKey)`:

```swift
                for subJSON in jsonArray {
                    guard let model = T(json: subJSON) else {
                        return nil  /// Previously this was an if let, not a guard
                    }
                    
                    models.append(model)
                }
```

I think that returning nil is the best default, but was wondering if there's an easy way to simulate 0.7.x behavior? 

Turns out one of the server endpoints I communicate with is giving back `null`s that I never noticed because of 0.7.x's behavior (which is why I approve of the change for 1.0 :) ), but want to simulate the old behavior on the client until I can update the server.  Since `null` isn't intended, I'd rather not change my struct to make the value Optional.

Would the easiest route be for me to write an extension method that simulates 0.7 behavior, something like:

```swift
extension Decoder {
    static func decodePartialArray<T>(key: String) -> [T] {
        // more or less copy/paste the 0.7 code in here
    }
}
```

For 1.1, what do you think of adding a `<~~!` or other operator that emulates the old behavior?

**Comment by hkellaway** [comment]
you are correct, that did change as of `0.8.0` (reference: https://github.com/hkellaway/Gloss/issues/189) - to be more consistent with how the rest of decoding is done.

i would recommend you do exactly what you suggested with `decodePartialArray` there.

i'm of the mind to keep the operator parlance of this library pretty focused, so i would likely not introduce that operator for that behavior. 

but, you could actually include `decodePartialArray` in your own application and create the operator yourself. i haven't tested this code, but it'd look something like this:

```
infix operator <~~! : DecodingPrecedence


func <~~! <T>(key: String, json: JSON) -> T? {
    return Decoder.decodePartialArray(key: key, json: json)
}
```

**Comment by ryanschneider** [comment]
Thanks for the feedback (and a great framework in general!).  I agree with keeping the operators focused, so opted not to implement my own either.

And for future reference in case anyone else runs into the same issue, here's my extension:

```swift
extension Decoder {
    /**
     Decodes JSON to a Decodable object array.  Emulates pre-0.8 behavior
     where elements of the JSON array that cannot be converted to T are skipped instead
     of returning nil.

     - parameter decodePartialArrayForKey: Key used in JSON for decoded value.

     - returns: Array of values that could be decoded from JSON, or nil if key is not found.
     */
    public static func decode<T: Decodable>(decodePartialArrayForKey key: String) -> (JSON) -> [T]? {
        return {
            json in

            if let jsonArray = json[key] as? [JSON] {
                var models: [T] = []

                for subJSON in jsonArray {
                    if let model = T(json: subJSON) {
                        models.append(model)
                    }
                }

                return models
            }

            return nil
        }
    }
}
```

Usage like so:
```swift
// Replace:
let arr: [Value]? = "values" <~~ json
// With:
let arr: [Value]? = Decoder.decode(decodePartialArrayForKey: "values")(json)
```
