### ISSUE TITLE
decoder returns function

### ISSUE THREAD

**Issue by mwk24** [hkellaway/Gloss#222]
Maybe I'm missing something but built-in Decoder functions seem to return (JSON) -> Thing? . Which produces a "Cannot assign value of type 'JSON -> NSDate?' to type 'NSDate?'", for example.

The example of how to extend Decode returns just Thing? which makes more sense.

**Comment by hkellaway** [comment]
it does return a function, not for good reason. i will be changing that in a subsequent version to improve clarity.

though decoding for Date works a bit differently as it is not binary (it also takes in a DateFormatter). to decode Dates you will lot use the <~~ operator.
