### ISSUE TITLE
Support for swift UUID type

### ISSUE THREAD

**Issue by Hiiragisan09** [hkellaway/Gloss#223]
Is it possible to add support for converting JSON to UUID with the <~~ operators?

**Comment by hkellaway** [comment]
i've never actually worked with UUIDs. is there a type (e.g. like `String`) for UUIDs?

**Comment by Hiiragisan09** [comment]
Yes, new in Swift3 the type `UUID`, previously you had to use `NSUUID`. https://developer.apple.com/reference/foundation/uuid and with `init?(uuidString: String)` you can parse a `String` to `UUID`

**Comment by Hiiragisan09** [comment]
I was waiting for this, and so i made it my self, pull request [https://github.com/hkellaway/Gloss/pull/226]. I also added unit testes to test the type. Maybe you can include it in the next release?

**Comment by hkellaway** [comment]
apologies for the delay at considering this. will review your PR this week

**Comment by hkellaway** [comment]
available as of `1.1.0` thanks to you! 🎉
