### ISSUE TITLE
Whenever the 'pod install' command is executed the Swift version setting is changed.

### ISSUE THREAD

**Issue by StateMachineJunkie** [hkellaway/Gloss#224]
The 'Use Legacy Swift Language Version' setting is changed from 'No' to 'Unspecified'. This breaks my build and I have to manually reset the value. Can you please submit a fix for this or tell me how to fix it within the Cocoapod so my CI doesn't fail?

**Comment by hkellaway** [comment]
This doesn't sound like an issue specific to Gloss. Perhaps try submitting this issue to the Cocoapods repo? https://github.com/CocoaPods/CocoaPods

**Comment by StateMachineJunkie** [comment]
For any who are interested, you need to update to CocoaPods 1.1.0 (gem install cocoapods --pre or using Bundler) for it to properly set the Swift version.
