### ISSUE TITLE
Strange tests in DecoderTests.swift

### ISSUE THREAD

**Issue by rbukovansky** [hkellaway/Gloss#230]
@hkellaway Hi, I'm wondering why do you test this:

`XCTAssertTrue((nanosecond/1000000 == 599), "Decode Date should return correct value")`

when in TestModel.swift you do have this:

`"date" : "2015-08-16T20:51:46.600Z",` ?

You set that date to 600 ms but testing it for 599? Could you please enlighten me? Do we lose that 1 ms somewhere? Thanks.

**Comment by hkellaway** [comment]
i don't have a good answer for that one. in the division we seem to lose a millisecond

**Comment by rbukovansky** [comment]
@hkellaway Well, we really do. What the hack?
But guess what... On Linux, it gets more messed up... https://bugs.swift.org/browse/SR-3116 :disappointed:
