### ISSUE TITLE
Swift_2.3 branch

### ISSUE THREAD

**Issue by yklishevich** [hkellaway/Gloss#231]
Hi. Branch swift_2.3 seems to have Swift3.0 code. It is not compiled when setting SWIFT_VERSION build setting to 2.3 and compiled when setting it to 3.0.

**Comment by hkellaway** [comment]
I've yet to have a chance to look into this. were you able to resolve or try using a previous version in the interim?

**Comment by ashishonmobile** [comment]
I guess same problem for me. I am new to swift. and trying to integrate it to one of my project.

**Comment by philmuse** [comment]
I did a checkout of the swift2_3 branch and it appears to include 3.0 syntax and compile options.  When I try to add to my Swift 2.3 project, I get error about Gloss being built as 3.0x.  I'm happy to pull earlier version of code, do you have a commit date or TAG to recommend?  Thanks.  And thanks for making this available to the community, it looks really cool.

**Comment by hkellaway** [comment]
anything `0.8.0` and prior is Swift 2.3 syntax

**Comment by hkellaway** [comment]
sorry about that, moved `swift_2.3` back to `0.8.0`
