### ISSUE TITLE
One nil element in json array causes the whole array to be nil

### ISSUE THREAD

**Issue by 2Fun2Code** [hkellaway/Gloss#232]
Hi!

When decoding a json array where one or more elements are nil cases the returned  array [T]  to be nil. I think the returning array should be nil only if not found in the json.

I suggest changing the code in Decoder.swift at rows 159 - 163 from:
guard let model = T(json: subJSON) else {
      return nil
}

models.append(model)

to:
if let model = T(json: subJSON) {
      models.append(model)
}

**Comment by hkellaway** [comment]
this was actually a purposeful decision to keep the semantics more consistent. i.e. if the value is not present or valid see: https://github.com/hkellaway/Gloss/issues/189 and https://github.com/hkellaway/Gloss/pull/197

if you'd like to implement a different behavior, you could consider your own transformations (https://github.com/hkellaway/Gloss#custom-transformations)
