### ISSUE TITLE
toJSON() returning array instead of object

### ISSUE THREAD

**Issue by bitkill** [hkellaway/Gloss#235]
Hi, I'm using Gloss to convert from and to json the following:

```
struct JSONPoint : Glossy {
    let audioCredits: Int
    let codename: String!
    let color: String?
    let coverImage: Int
    let customQRCode: String!
    let dateEnd: NSDate?
    let dateStart: NSDate?
    let descriptionCredits: Int
    let displayExtended: Bool
    let displayInMap: Bool
    let enabled: Bool
    let galleryCredits: Int
    let iBeaconCode: String!
    let iconId: Int?
    let id: Int
    let listOrder: Int
    let panoramaPoints: Int
    let parentId: Int?
    let positionX: Float?
    let positionY: Float?
    let positionZ: Float?
    let updatedAt: NSDate!


    public init?(json: JSON){
      ...
    }

    public func toJSON() -> JSON? {
        return jsonify([
            "audioCredits" ~~> self.audioCredits,
            "codename" ~~> self.codename,
            "color" ~~> self.color,
            "coverImage" ~~> self.coverImage,
            "dateEnd" ~~> self.dateEnd,
            "dateStart" ~~> self.dateStart,
            "displayExtended" ~~> self.displayExtended,
            "displayInMap" ~~> self.displayInMap,
            "enabled" ~~> self.enabled,
            "iconId" ~~> self.iconId,
            "listOrder" ~~> self.listOrder,
            "parentId" ~~> self.parentId,
            "positionX" ~~> self.positionX,
            "positionY" ~~> self.positionY,
            "positionZ" ~~> self.positionZ
        ])
    }
}
```

My current output is the following (array, invalid) :

`Optional(["positionY": -0.884366989, "displayInMap": true, "enabled": true, "positionX": -0.502907991, "codename": "Azenha", "listOrder": 4, "color": "cf6728", "displayExtended": true, "parentId": 53, "coverImage": 431, "positionZ": -1.00127006, "iconId": 0, "audioCredits": 0])`

I expected this (object, valid):

`Optional({"positionY": -0.884366989, "displayInMap": true, "enabled": true, "positionX": -0.502907991, "codename": "Azenha", "listOrder": 4, "color": "cf6728", "displayExtended": true, "parentId": 53, "coverImage": 431, "positionZ": -1.00127006, "iconId": 0, "audioCredits": 0})`

**Comment by hkellaway** [comment]
i'm not sure i understand - both appear to be dictionaries. the syntax in the first one (i.e. key-value pairs) wouldn't make sense for an array. 

did you find when running your code that the object retrieved from `toJSON()` was an array? that couldn't be. or, perhaps, what you're pasting here what you see in the console..?

**Comment by bitkill** [comment]
Sorry, my bad. Still getting used to swift "JSON as dictionary" approach to converting stuff.
The output I posted was from the console. I eventually needed the String to tunnel back to a WKWebView and was not getting the "String", just the dictionary.

This did the trick:

```
    func getPointsForJs() {
        
        var allPoints = [JSONPoint]()
        
        DatabaseApi.sharedInstance.allPoints().forEach { point in
            let jPoint = JSONPoint(coreData: point)
            allPoints.append(jPoint)
        }
        
        
        let jsonData = try! JSONSerialization.data(withJSONObject: allPoints.toJSONArray()!, options: [])
        let sPoints : String = String(data: jsonData, encoding: String.Encoding.utf8)!
        
        
        let jsCode = "NativeInterface.setPoints({ \"points\": \(sPoints) })"
        
        print(jsCode)
        
        webView!.evaluateJavaScript(jsCode, completionHandler: nil)
    }
```

I'm wondering if a function that converts from the dictionary to string would be a good idea.
Anyway, thanks for the reply :)

**Comment by hkellaway** [comment]
no problem :)
