### ISSUE TITLE
Why is Gloss percent-escaping URLs?

### ISSUE THREAD

**Issue by ryanschneider** [hkellaway/Gloss#238]
Question for you, I was seeing my URLs get mysteriously double-percent encoded and finally tracked it down to these lines in Decoder.swift:

```swift
public static func decode(urlForKey key: String, keyPathDelimiter: String = GlossKeyPathDelimiter) -> (JSON) -> URL? {
        return {
            json in
            
            if let urlString = json.valueForKeyPath(keyPath: key, withDelimiter: keyPathDelimiter) as? String,
                let encodedString = urlString.addingPercentEncoding(withAllowedCharacters: CharacterSet.urlQueryAllowed) {
                return URL(string: encodedString)
            }
            
            return nil
        }
    }
```

What's the reasoning for percent encoding in here?  IMO, this should be an optional behavior of Decoder.decode(urlForKey:) rather than the default / `<~~` behavior.  

My rationale is that if the JSON input's URL is already sanely escaped, this leads to it being double escaped, when IMO it should the invalid URL case that needs to be specially handled.

Also, FWIW, it looks like Decoder.decode(urlArrayForKey:) doesn't do this percent escaping, so if this behavior is fixing a bug I'm not aware of, the bug might be raring it's head when decoding URL arrays.

For now, I'm working around this double percent escaping by doing things like:

```swift
struct Foo: Glossy {
  var bar: URL

  init?(json: JSON) {
     guard let s: String = "bar" <~~ json, let url: URL = URL(string: s) else { return nil }
     self.bar = url
  }

  //...
}
```

Which works for me but isn't intuitive.

Thanks!

**Comment by hkellaway** [comment]
that was a change made here https://github.com/hkellaway/Gloss/pull/119

and, good point, it should have been applied to `urlArray` as well

@ejmartin504 can you chime in again here as to why you think the escaping is a good idea ?

**Comment by niedfelj** [comment]
This is also breaking URLs with a fragment:

https://medium.com/the-coffeelicious/the-flaw-of-love-77a848c7703e#.54mta71a9

Gloss turns that into:

https://medium.com/the-coffeelicious/the-flaw-of-love-77a848c7703e%23.54mta71a9

Which then 404's on the Medium site

**Comment by hkellaway** [comment]
removed escaping as of version `1.2.0`!

**Comment by ejmartin504** [comment]
whoops @hkellaway didn't see this until just now. I added it mainly because of some URLs on a project that weren't getting decoded properly. But really that's the responsibility of the backend, not the client in this case. Glad it got cleared up!
