### ISSUE TITLE
enumArrayForKey should not be exclusive to the enum type

### ISSUE THREAD

**Issue by ed-mejia** [hkellaway/Gloss#239]
Enum arrays (Decoder.decode(enumArrayForKey:)) forces you to have all values in the array the same type of the enum, e.g

```
enum Color {
  case blue
  case red
}

enum Element {
  case fire
  case wind
}

//JSON
"color_elements": {
  "blue",
  "fire",
  "red",
  'wind'
}
```

If I apply:

`self.colors =  Decoder.decode(enumArrayForKey: "color_elements")(json) ?? []`

I would expect to have an array back with only the colors, but I'm getting back an empty array because there is a different type within the **color_elements** object

**Comment by hkellaway** [comment]
that was intentional. arrays in Swift are homogenous, i would not expect to have an array of various enum types. if that is something your application does have, i'd contend you should create a [custom transformation](https://github.com/hkellaway/Gloss#custom-transformations)]

**Comment by ed-mejia** [comment]
In my case color_elements is homogenous, but contains a value not present in the enum... I think that should not avoid the generation of the array... just ignore it... all values are the same type of the enums "Strings"

**Comment by ed-mejia** [comment]
Let me know what do you think about this, otherwise I will follow your suggestion about creating a custom transformation for this case and we can close this issue.

**Comment by hkellaway** [comment]
it seems to me this issue is similar in nature to this one - https://github.com/hkellaway/Gloss/issues/189

i.e. what is the expected behavior for unexpected input. in that issue, we resolved that for unexpected input, decoding functions that returned arrays would not return partial or empty arrays but would return `nil`.

this is a bit different in that what programmatically unifies enums is that they are `RawRepresentable` - but from a model point of view, what unifies them is that they are of the same "type", i.e. belong to the same enum. 

i'm still of the mind that having an enum array with the same types is what is expected.

**Comment by ed-mejia** [comment]
Fair enough, I will go with the custom transformation.

Thanks 👍

**Comment by ed-mejia** [comment]
Sorry for the re-opening...

I think actually that way of working is introducing limitations to the library.

For example I'm actually working on a news feed api, it could return different types of objects under the same root container "items" this way:

```
{
  "data": {
    "pagination": {
        "total": 11124,
        "per_page": 30,
        "offset": 0
    },
    "items": [
      {
        "picture": "Some picture"
      },
     {
       "story": "Some Story"
     },
    {
      "video": "Some video"
    }
    ]
 }
}

```

The library now requires all elements within items must be the same model, which is a very rude... so now I **can't** do something like this 

pictureList = "items" <~~ data ?? []
storyList = "items" <~~ data ?? []
videoList = "items" <~~ data ?? []

because the library will stop parsing all element in the array....  I think the idea should be to facilitate functionality not to impose a particular way of thinking? 

I think it **should not be considered as a parsing error** to find some different element type within the parsing array... the lib is not being open to "internet" in which many requirements and many situations might me present.

What do you think with this scenario?

**Comment by hkellaway** [comment]
no problem reopening, of course.

i don't see this as rude, but opinionated - the library expects homogenous arrays and will carry on effortlessly in that case. i find the potential for partial arrays adds an element of surprise to the output the library has, that i'd rather the specific application _explicitly_ handle. that's how i personally  expect JSON libraries to behave; i took that original cue from other libraries like Mantle.

**Comment by ed-mejia** [comment]
Yep, opinionated... 

It is a restriction based on an opinion of how should behave, of course there is no right and wrong with this case.

Would be nice at least, to provide the option and **let the users decide** how they whant to use the library instead of forcing a particular point of view of how **they** should do it, well that's just my opinion.

So yes... I will have to follow the custom transformation way for everything that implies this scenario, even for normal arrays 😩

**Comment by ed-mejia** [comment]
@hkellaway  Any chance to make the behaviour optional to let users decide how they need the lib to behave in these particular scenarios?

I'm ok dealing with a custom transformation for enums, but doing the same for general arrays doesn't feels right.

**Comment by hkellaway** [comment]
alright. something like including an 'allowPartialArrays' flag argument that is defaulted to 'false' in the operator definitions? or did you have another implementation in mind? and would you be willing to make a pull request to that effect?

**Comment by ed-mejia** [comment]
Sure, I would make a pull request tomorrow I already did some testing using Protocol conformance instead of a flag.

My idea, in order to do not mess with the actual implementation is to create additional protocols 

```
public protocol PartiallyDecodable: Decodable { }
public protocol PartiallyEncodable: Encodable { }
```

This way if you need to make your model "partially" decodable or encodable you just conform to this protocol, no need for a flag messing around 👍 and it could apply to any array type (enums, structs, class)

**Comment by ed-mejia** [comment]
Not sure about naming though!..

Because the idea of this is that it will apply when parsing arrays of the models implementing those protocols, if I see any model implementing that I could think it means that the actual model could be somehow partially parsed which is not correct.

thinking about it...
