### ISSUE TITLE
Can I Use A Recursive Inside Decodable Struct?

### ISSUE THREAD

**Issue by luthfifr** [hkellaway/Gloss#241]
Hi, I have a JSON that looks like this:
{
	"success": true,
	"terms": "https:\/\/currencylayer.com\/terms",
	"privacy": "https:\/\/currencylayer.com\/privacy",
	"timestamp": 1480584613,
	"source": "USD",
	"quotes": {
		"USDAED": 3.672501,
		"USDAFN": 66.550003,
		"USDALL": 127.199997,
		"USDAMD": 479.700012,
		"USDANG": 1.769562,
		"USDAOA": 165.074005,
		"USDARS": 15.719816,
		"USDAUD": 1.3518,
		"USDAWG": 1.79,
		"USDAZN": 1.731298,
		"USDBAM": 1.845102,
		"USDBBD": 2,
		"USDBDT": 78.750148,
		"USDBGN": 1.839098,
		"USDBHD": 0.37675,
		"USDBIF": 1668.810059,
		"USDBMD": 1,
		"USDBND": 1.427502,
		"USDBOB": 6.860222,
		"USDBRL": 3.408303,
		"USDBSD": 1,
		"USDBTC": 0.001337,
		"USDBTN": 68.449997,
		"USDBWP": 10.770897,
		"USDBYR": 20020,
		"USDBZD": 1.979909,
		"USDCAD": 1.34134,
		"USDCDF": 1143.000097,
		"USDCHF": 1.01449,
		"USDCLF": 0.02544,
		"USDCLP": 675.73999,
		"USDCNY": 6.895197,
		"USDCOP": 3072.800049,
		"USDCRC": 545.750515,
		"USDCUC": 1,
		"USDCUP": 1.000334,
		"USDCVE": 104.000181,
		"USDCZK": 25.479502,
		"USDDJF": 177.899994,
		"USDDKK": 7.00729,
		"USDDOP": 46.290001,
		"USDDZD": 110.250146,
		"USDEEK": 14.731039,
		"USDEGP": 17.700001,
		"USDERN": 15.30318,
		"USDETB": 22.272799,
		"USDEUR": 0.941598,
		"USDFJD": 2.08498,
		"USDFKP": 0.798102,
		"USDGBP": 0.79776,
		"USDGEL": 2.525196,
		"USDGGP": 0.797815,
		"USDGHS": 4.320022,
		"USDGIP": 0.798298,
		"USDGMD": 40.619999,
		"USDGNF": 9144.999895,
		"USDGTQ": 7.5115,
		"USDGYD": 204.779999,
		"USDHKD": 7.75536,
		"USDHNL": 23.000201,
		"USDHRK": 7.063998,
		"USDHTG": 66.650002,
		"USDHUF": 294.630005,
		"USDIDR": 13542,
		"USDILS": 3.827497,
		"USDIMP": 0.797815,
		"USDINR": 68.324997,
		"USDIQD": 1160.400024,
		"USDIRR": 32091.000218,
		"USDISK": 111.550003,
		"USDJEP": 0.797815,
		"USDJMD": 128.839996,
		"USDJOD": 0.7078,
		"USDJPY": 114.203003,
		"USDKES": 101.699997,
		"USDKGS": 69.130997,
		"USDKHR": 4002.000174,
		"USDKMF": 464.000254,
		"USDKPW": 899.99985,
		"USDKRW": 1167.599976,
		"USDKWD": 0.304804,
		"USDKYD": 0.820006,
		"USDKZT": 339.498593,
		"USDLAK": 8170.000271,
		"USDLBP": 1506.199951,
		"USDLKR": 147.800003,
		"USDLRD": 90.999896,
		"USDLSL": 14.07024,
		"USDLTL": 3.048702,
		"USDLVL": 0.62055,
		"USDLYD": 1.423986,
		"USDMAD": 10.065974,
		"USDMDL": 20.200001,
		"USDMGA": 3327.000018,
		"USDMKD": 57.630001,
		"USDMMK": 1316.999867,
		"USDMNT": 2455.000352,
		"USDMOP": 7.987799,
		"USDMRO": 355.000006,
		"USDMUR": 36.049999,
		"USDMVR": 15.115787,
		"USDMWK": 716.299988,
		"USDMXN": 20.567301,
		"USDMYR": 4.4588,
		"USDMZN": 74.050003,
		"USDNAD": 14.001986,
		"USDNGN": 314.000072,
		"USDNIO": 29.207099,
		"USDNOK": 8.48281,
		"USDNPR": 109.260002,
		"USDNZD": 1.410596,
		"USDOMR": 0.384902,
		"USDPAB": 1,
		"USDPEN": 3.412802,
		"USDPGK": 3.172103,
		"USDPHP": 49.730315,
		"USDPKR": 104.800003,
		"USDPLN": 4.200199,
		"USDPYG": 5829.000336,
		"USDQAR": 3.641009,
		"USDRON": 4.242498,
		"USDRSD": 115.590401,
		"USDRUB": 63.999901,
		"USDRWF": 808.809998,
		"USDSAR": 3.750599,
		"USDSBD": 7.997501,
		"USDSCR": 13.18603,
		"USDSDG": 6.480698,
		"USDSEK": 9.22865,
		"USDSGD": 1.42897,
		"USDSHP": 0.798302,
		"USDSLL": 5541.000011,
		"USDSOS": 548.000021,
		"USDSRD": 7.260397,
		"USDSTD": 23050,
		"USDSVC": 8.722199,
		"USDSYP": 515.000091,
		"USDSZL": 13.989001,
		"USDTHB": 35.689999,
		"USDTJS": 7.876295,
		"USDTMT": 3.4,
		"USDTND": 2.306008,
		"USDTOP": 2.280102,
		"USDTRY": 3.455397,
		"USDTTD": 6.719791,
		"USDTWD": 31.879999,
		"USDTZS": 2174.999776,
		"USDUAH": 25.519868,
		"USDUGX": 3625.000111,
		"USDUSD": 1,
		"USDUYU": 28.999853,
		"USDUZS": 3169.999612,
		"USDVEF": 9.975021,
		"USDVND": 22640,
		"USDVUV": 107.029999,
		"USDWST": 2.5629,
		"USDXAF": 617.419983,
		"USDXAG": 0.060846,
		"USDXAU": 0.000855,
		"USDXCD": 2.699844,
		"USDXDR": 0.738682,
		"USDXOF": 616.900024,
		"USDXPF": 111.699997,
		"USDYER": 250.000244,
		"USDZAR": 14.035022,
		"USDZMK": 5156.099912,
		"USDZMW": 9.869862,
		"USDZWL": 322.355011
	}
}

To deserialize it I need 2 decodable stucts:
one looks like this:
       struct CurrencyList: Decodable {
        let success: String?
        let terms: String?
        let privacy: String?
        let timestamp: String?
        let source: String?
        let quotes: CurrencyQuotes?
        
        init?(json: JSON) {
            self.success = "success" <~~ json
            self.terms = "terms" <~~ json
            self.privacy = "privacy" <~~ json
            self.timestamp = "timestamp" <~~ json
            self.source = "source" <~~ json
            self.quotes = "quotes" <~~ json
          }
        }

and the other looks like this: //the list of this items is 2x167 long.
struct CurrencyQuotes: Decodable{
   let USDAED: Double?
   let USDAFN: Double?
   ....
   let USDZMW: Double?
   let USDZWL: Double?

   init?(json: JSON){
        self.USDAED = "USDAED" <~~ json
        self.USDAFN = "USDAFN" <~~ json
        ....
        self.USDZMW = "USDZMW" <~~ json
        self.USDZWL = "USDZWL" <~~ json
   }
}

I wanna ask you whether there is any possibilities to use recursive in the second struct so it will look more simple?

**Comment by hkellaway** [comment]
i am not sure looking at that how recursion might address an issue. if you find you can, read the section in the README on including your own Custom Transformations
