### ISSUE TITLE
[question] Implement Decodable in an extension

### ISSUE THREAD

**Issue by frootloops** [hkellaway/Gloss#242]
Hello,

I want to separate Business Model and encode/decode functionality. So I think the best way to do it it's move encode/decode method to an extension.

I can do next:

```
final class User {
    let name: String
    
    init(name: String) {
        self.name = name
    }
}

extension User: Decodable {

    convenience init?(json: JSON) {
        let name: String = "name" <~~ json ?? ""
        self.init(name: name)
    }
}
```

But it requites to use `final` keyword. So I cannot use inheritance anymore. But it's not suitable for me. Any other ways to separate Business Model and encode/decode functionality?

Thanks.

**Comment by hkellaway** [comment]
I've not written extensions much myself and do not have a way to get around a 'final' requirement while using inheritance. if anyone reading does, please chime in.

**Comment by gerbiljames** [comment]
This is the best I could come up with while still allowing User to be subclassed:

```swift
class User {
  let name: String
  
  init(name: String) {
    self.name = name
  }
}

extension User {
  struct JSONInitializer: Decodable {
    let model: User
    init?(json: JSON) {
      let name: String = "name" <~~ json ?? ""
      model = User(name: name)
    }
  }
}
```

But it means you have to initialize your models like this: 

```swift
let user = User.JSONInitializer(json: ["name": "James"])?.model
```
which is ugly and unintuitive.

**Comment by frootloops** [comment]
@gerbiljames yes, it's kind of ugly

**Comment by hkellaway** [comment]
i just read this this morning:

"`dynamic` can be used to allow methods declared in extensions to be overridden"

https://www.raizlabs.com/dev/2016/12/swift-method-dispatch

i haven't tried it myself though

**Comment by heshamsalman** [comment]
@frootloops what you're doing is currently unsupported by the Swift language. There's a bug report filed here: http://www.openradar.me/23358609 but it's been around for a while. 

It may be worth mentioning that what you're doing is _completely_ valid for structs. 

```swift
struct User {
    let name: String
}

extension User: Decodable {
    init?(json: JSON) {
        let name: String = "name" <~~ json ?? ""
        self.init(name: name)
    }
}
```
