### ISSUE TITLE
How to return String?

### ISSUE THREAD

**Issue by TheSDTM** [hkellaway/Gloss#246]
Hello. How to return JSON string like `{"id": "1", "login": "qwerty"}` from this model?

```
func toJSON() -> JSON? {
        return jsonify([
            "id" ~~> self.ownerId,
            "login" ~~> self.username
        ])
    }
```

It returns JSON type, but I need String to save it to file. Thank you.

**Comment by hkellaway** [comment]
there's nothing within Gloss to do that. i'd consider conforming your models to `CustomStringConvertible` and providing the required `description` variable.
