### ISSUE TITLE
Allow non-Optional properties

### ISSUE THREAD

**Issue by hkellaway** [hkellaway/Gloss#25]
Suggested by @Haud

**Comment by Haud** [comment]
Yes!

I've had time to take a deeper look into the code base. My thoughts are maybe we can have two operators: `<~?` for optional and `<~!` for non-optional. I think it's more immediately clear that way which operator does what, though I'm ok with `<~~` and a non-optional type: `<~~!` or something.

I would also be more in favor of a `init( json: JSON)` as the protocol method than `fromJSON`, though I do understand its semantic equivalent in Encoder's `toJSON`

**Comment by hkellaway** [comment]
good suggestions! i'll keep you posted

**Comment by hkellaway** [comment]
the referenced PRs take your suggestions into account. non-optional properties are now allowed by using `forceDecode_` functions or by using the `<~~!` operator. Additionally, I did like the idea of having to initialize with JSON, so the `Decodable` protocol was updated to reflect that.

you'll see these updates in 0.4.0 :boom:
