### ISSUE TITLE
[question] I want to convert struct to JSON, struct have a optional value is nil

### ISSUE THREAD

**Issue by xudegithub** [hkellaway/Gloss#251]
like this 

```
struct GoListUpdateSequenceModel: Encodable {
    let id: Int?
    let label: String
    let type: String
    let items: [GoListUpdateSequenceItemModel]
    func toJSON() -> JSON? {
        return jsonify([
            "id" ~~> self.id ,
            "label" ~~> self.label,
            "type" ~~> self.type,
            "items" ~~> self.items,
            ])
    }
}
```
if id is nil, after convert toJSON(), i get JSON like this: "[{\"type\":\"label\",\"label\":\"Divieder\",\"items\":[{\"type\":\"place\",\"id\":12964}]}]"
I want to get "[{\"id\":null,\"type\":\"label\",\"label\":\"Divieder\",\"items\":[{\"type\":\"place\",\"id\":12964}]}]"
can you help me? 
sorry for my english.

**Comment by hkellaway** [comment]
you'll probably want to create your own encoding function (see Custom Transformations: https://github.com/hkellaway/Gloss#custom-transformations)
