### ISSUE TITLE
Changable JSON array's properties

### ISSUE THREAD

**Issue by ttuygun** [hkellaway/Gloss#252]
Hi! My JSON array's properties is changable and this causes decoding error.
Normally it works in stardart array:
[{
 "type": "text",
 "text": "bblaa"
},
 "type": "text",
 "text": "bblaa"
}]
it's ok and no problem with it but sometimes the array's second item will change like this:
[{
 "type": "text",
 "text": "bblaa"
},
 "type": "image",
 "image_url": "bblaa"
}]

```
import Gloss

struct MobileEntryGloss: Decodable {

    var type: String?
    var text: String?

    init?(json: JSON) {
        guard let type: String = "type" <~~ json else {
            print("Error decoding with type")
            return nil
        }
        guard let text: String = "text" <~~ json else {
            print("Error decoding with text")
            return nil
        }
        self.type = type
        self.text = text
    }
    
}
```
I tried to traverse the first array's of the item but it don't work. Is there any feature like "mobile.0.text" or different approach? 
note: mobile is the upper object of my JSON example

**Comment by hkellaway** [comment]
there isn't a feature like that. you may need to get creative with a Custom Transformation - here's an example https://github.com/hkellaway/Gloss/issues/113
