### ISSUE TITLE
Why everything is packed into JSONArrays?

### ISSUE THREAD

**Issue by Progern** [hkellaway/Gloss#254]
It may be dumb, but I just can't find the answer to this question.
I want to create a JSON-file from Array of Objects of some type (to serialize this array into JSON object)
Each object of this type has an array of other objects inside

My models implement func toJSON()  like this
`func toJSON() -> JSON? {
        
        return jsonify([
            "id" ~~> self.id,
            "start" ~~> self.start,
        "end" ~~> self.end,
    "desc" ~~> self.desc])
 
    }`

But each object in array is an array too. Help me pls

**Comment by hkellaway** [comment]
i don't quite understand what you're describing. can you provide an example of the JSON?

**Comment by Progern** [comment]
I need to create something like this

`{
   "objects":[
      {
         "value1":"4278255360",
         "value2":"",
         "value3":"472632b338",
         "key_value":"68",
         "name_value":"Hello",
         "nested_objects":[
            {
               "desc":"",
               "first_value":"40.979",
               "value3":"701dee3003eee",
               "second_value":"38.166"
            }
         ],
         "sortOrder":"4"
      }
   ]
}`

But I get something like this

`[   "objects":[      [        "value1":"4278255360",         "value2":"",         "value3":"472632b338",         "key_value":"68",         "name_value":"Hello",         "nested_objects":[            [               "desc":"",               "first_value":"40.979",               "value3":"701dee3003eee",               "second_value":"38.166"            ]        ],         "sortOrder":"4"      ] ] ]`

Where I need objects, they are arrays.  For example, we have an array called "objects", but in my case this is an array of arrays.. I need an array of objects.

**Comment by hkellaway** [comment]
given that JSON, you could create your models as such:

``` swift
struct ObjectCollection: Glossy {
    
    let objects: [Object]?
    
    init?(json: JSON) {
        self.objects = "objects" <~~ json
    }
    
    func toJSON() -> JSON? {
        return jsonify([
            "objects" ~~> self.objects
            ])
    }
    
}

struct Object: Glossy {
    
    let value1: String?
    let value2: String?
    let value3: String?
    let keyValue: String?
    let nameValue: String?
    let nestedObjects: [NestedObject]?
    let someOrder: String?
    
    init?(json: JSON) {
        self.value1 = "value1" <~~ json
        self.value2 = "value2" <~~ json
        self.value3 = "value3" <~~ json
        self.keyValue = "key_value" <~~ json
        self.nameValue = "name_value" <~~ json
        self.nestedObjects = "nested_objects" <~~ json
        self.someOrder = "some_order" <~~ json
    }
    
    func toJSON() -> JSON? {
        return jsonify([
            "value1" ~~> self.value1,
            "value2" ~~> self.value2,
            "value3" ~~> self.value3,
            "key_value" ~~> self.keyValue,
            "name_value" ~~> self.nameValue,
            "nested_objects" ~~> self.nestedObjects,
            "some_order" ~~> self.someOrder
            ])
    }
    
}

struct NestedObject: Glossy {
    
    let anotherValue: String?
    let firstValue: String?
    let value3: String?
    let secondValue: String?
    
    init?(json: JSON) {
        self.anotherValue = "another_value" <~~ json
        self.firstValue = "first_value" <~~ json
        self.value3 = "value3" <~~ json
        self.secondValue = "second_value" <~~ json
    }
    
    func toJSON() -> JSON? {
        return jsonify([
            "another_value" ~~> self.anotherValue,
            "first_value" ~~> self.firstValue,
            "value3" ~~> self.value3,
            "second_value" ~~> self.secondValue
            ])
    }
    
}
```

and deserialization/serialization:

``` swift
guard let objects = ObjectCollection(json: json) else {
        print("Failed deserialization")
        return
}
        
print(objects.objects)
        
guard let objectsJSON = objects.toJSON() else {
        print("Failed serializtation")
        return
}
        
print(objectsJSON)
```

**Comment by Progern** [comment]
Can I avoid init?() if i just need my objects to be packed into JSON?

**Comment by hkellaway** [comment]
yes, simply conform to 'Encodable' instead of 'Glossy'

**Comment by Progern** [comment]
Btw, thank you for responding to my, maybe, stupid questions. Your library is best opensource so I wish to use it now and in all my next projects.
I changed to Encodable. **I guess the problem is in calling function jsonify([])** cause it returns a JSON Array, or am I wrong? I have this function in my class model (I'm not using structures btw, can the problem be in this?)  So every time it is called with an independent object it creates a JSON Array for one object.

**Comment by hkellaway** [comment]
jsonify() does not return an array, it returns the Gloss type JSON - which is a dictionary of [String : Any]
