### ISSUE TITLE
The target “Gloss” contains source code developed with an earlier version of Swift.

### ISSUE THREAD

**Issue by frios** [hkellaway/Gloss#255]
When I use 
pod 'Gloss', '~> 1.1'
to integrate Gloss into my project. When I do so, I get the "Convert to current Swift Syntax" message. My project is Swift 3.0. Should't the pod be downloading from the Swift 3.0 branch?

**Comment by heshamsalman** [comment]
By any chance, do you have a post install script which forcefully sets swift version on pods? 

If you do: 
- pod deintegrate 
- update your cocoapods version
- go to your project and set your project target swift version to Unspecified
- remove the post install script from your pod file 
- pod install

**Comment by frios** [comment]
I actually got it all working. Seemed to be a cocoapods issue. Thank you. 

FGR
