### ISSUE TITLE
Using Gloss in Share Extensions?

### ISSUE THREAD

**Issue by shamikagasc** [hkellaway/Gloss#259]
Has anyone had any issues submitting an app extension that uses Gloss? I want to use Gloss in my share extension but I am currently seeing **linking against a dylib which is not safe for use in application extensions** warnings

**Comment by hkellaway** [comment]
Please follow this issue: https://github.com/hkellaway/Gloss/issues/242

**Comment by shamikagasc** [comment]
FYI my issue has nothing to do with #242 . To resolve it I had to navigate to the gloss target within the cocoapods project and set `Require Only App-Extension-Safe API` to `true`. 
Refer to https://github.com/CocoaPods/CocoaPods/issues/5373 for more information

**Comment by hkellaway** [comment]
sorry my mistake. thanks for sharing the fix!
