### ISSUE TITLE
Linux tests failing for creating models from Data

### ISSUE THREAD

**Issue by hkellaway** [hkellaway/Gloss#264]
@rbukovansky The ability to create models from `Data` was added last release, `1.2.0` - though the accompanying tests were not made available to `swift test`. Upon adding them, the Linux build fails on these test cases:

Test Case 'GlossTests.testModelFromJSONRawData'
Test Case 'GlossTests.testModelArrayFromJSONArrayRawData'

**Comment by rbukovansky** [comment]
@hkellaway I will take a look.

**Comment by hkellaway** [comment]
just checking in on this one - any movement

**Comment by rbukovansky** [comment]
@hkellaway I'm working on it... Slowly, but I'm... Just a lot's of work... 😢 Sorry. But I hope to have it resolved this weekend.

**Comment by hkellaway** [comment]
maybe we should keep `linux` support on a separate branch? that way if you need time to work on it, it doesn't block the development of the general library.

**Comment by rbukovansky** [comment]
@hkellaway Hi, I've got finally some time to look at this. Could you please make a merge of `develop` branch to `linux` branch? I tried to do that myself but got some conflicts I'm not sure if I would solve correctly. Thanks.

**Comment by hkellaway** [comment]
sure - just rebased `linux` on `develop`

**Comment by rbukovansky** [comment]
@hkellaway PR submitted. I'm probably going to unleash the hell on Swift devs, what's going on, why Swift/Linux is such a mess... :unamused:
