### ISSUE TITLE
Are the order of the attributes maintained when converting to JSON?

### ISSUE THREAD

**Issue by SnitramDev** [hkellaway/Gloss#265]
Are the order of the attributes maintained when converting to JSON?
I'm asking since the well known ObjectMapper library doesn't allow to do this. There are a few issues opened for this but it seems this is not possible to do in that library.

Is this the case for this library?

Thanks!

**Comment by hkellaway** [comment]
there is no guarantee that the order of attributes are maintained

**Comment by SnitramDev** [comment]
Does this happen due to the design of the library or because of the iOS's JSONSerialization class itself? Is there a way to make this possible?

It's really important to maintain the order of the attributes, because if you serialize the json to NSData and you use an MD5 string to determine whether the data has changed, it's good to know that it hasn't.

**Comment by hkellaway** [comment]
there is no implementation in the library that attempts to maintain some sort of order - and its not a feature that's intended to be supported. of course, folks can submit pull requests to that effect
