### ISSUE TITLE
Converting from strings in json to integer expected types

### ISSUE THREAD

**Issue by crspybits** [hkellaway/Gloss#268]
My json coming to my server typically looks like:

{
   "intfield" : "42"
}

but when I use an Int32 field in my models, this fails.

Are you open to adding String alternative cases like that below?

```
    public static func decode(int32ForKey key: String, keyPathDelimiter: String = GlossKeyPathDelimiter) -> (JSON) -> Int32? {
        return {
            json in
            
            if let number = json.valueForKeyPath(keyPath: key, withDelimiter: keyPathDelimiter) as? NSNumber {
                return number.int32Value
            }
            
            if let string = json.valueForKeyPath(keyPath: key, withDelimiter: keyPathDelimiter) as? String {
                return Int32(string)
            }
            
            return nil
        }
    }
```

**Comment by hkellaway** [comment]
i'm open to considering that, but don't have the bandwidth right now to implement myself

if desired, can you submit a pull request to that effect? it should also include `Int64` as well as `UInt32` and `UInt64`, and all their array counterparts. and tests should be updated to reflect that such values can be created from `String`s.

**Comment by crspybits** [comment]
Thanks-- I'll see if I can get on that.
