### ISSUE TITLE
Don't return 'nil' if one object fails decoding in: decodableArrayForKey.

### ISSUE THREAD

**Issue by jsonfellin** [hkellaway/Gloss#275]
Love the library, thanks.

One small suggestion.

For the following method, and others related, could I suggest not returning nil for the entire Array if only one Element fails decoding?

So

```
public static func decode<T: Decodable>(decodableArrayForKey key: String, keyPathDelimiter: String = GlossKeyPathDelimiter) -> (JSON) -> [T]? {
        return { json in
            
            if let jsonArray = json.valueForKeyPath(keyPath: key, withDelimiter: keyPathDelimiter) as? [JSON] {
                var models: [T] = []
                
                for subJSON in jsonArray {
                    guard let model = T(json: subJSON) else {
                        return nil
                    }
                    
                    models.append(model)
                }
                return models
            }
            
            return nil
        }
    }
```

Could become:

```
public static func decode<T: Decodable>(decodableArrayForKey key: String, keyPathDelimiter: String = GlossKeyPathDelimiter) -> (JSON) -> [T]? {
        return { json in
            
            if let jsonArray = json.valueForKeyPath(keyPath: key, withDelimiter: keyPathDelimiter) as? [JSON] {
                var models: [T] = []
                
                for subJSON in jsonArray {
                    if let model = T(json: subJSON) else {
                        models.append(model)
                    }
                }
                
                if models.count > 0 { return models }
            }
            return nil
        }
    }
```

That way if an endpoint sends some objects that fail decoding, they fail silently and the Elements that succeeded are added to the Array.

Thoughts?

**Comment by hkellaway** [comment]
this was thought about - the ultimate conclusion being its more consistent with the rest of the decoding functions to return `nil` (https://github.com/hkellaway/Gloss/issues/189). for your case, you could do a custom transformation (https://github.com/hkellaway/Gloss#custom-transformations)

**Comment by jsonfellin** [comment]
Thanks for responding. 

I would argue returning nil only makes sense on the single object level, not a collection. Why would I ever want to return `nil` for an Array or Dictionary if more than zero of its Elements are decoded successfully?

I know about the custom decoders and have already written one for this purpose. This was to be used on a property with a generic type, hence the convenience factor.
