### ISSUE TITLE
decoding null to optional produces warning in console

### ISSUE THREAD

**Issue by vgillestad** [hkellaway/Gloss#279]
I have a struct like this:
```
struct Foo : Decodable {
    let id:String?
    
    init?(json: JSON) {
        self.id = "id" <~~ json
    }
}
```

and the JSON I decode is like this:
```
{
    "id":null
}
```

After updating to latest version of Gloss I get a printout like this in the console:
**[Gloss] Value found for key "id" but decoding failed.**

Is there anyway to avoid this warning message in the console? At least if the value is null I would like this to "fail" silently.

**Comment by hkellaway** [comment]
in version `1.2.3` 🎉

**Comment by arbitur** [comment]
@hkellaway Still happening in `1.2.4` for me

**Comment by hkellaway** [comment]
can you provide the JSON and your Gloss model?

**Comment by arbitur** [comment]
@hkellaway It seems to be when trying to parse a Bool from integer 1 or 0. But it seem to work, my booleans get their correct value [true or false] but still getting the warning:

>[Gloss] Value found for key "paid" but decoding failed.

    // JSON
    {
        "paid": 1,
    }

    let isPaid: Bool
    init?(json: JSON) {
        isPaid = ("paid" <~~ json)!
    }

**Comment by elanovasconcelos** [comment]
I'm having the same problem, but with true/false in the json. And the result is nil

**Comment by hkellaway** [comment]
i tried your example - i do not get a boolean value, rather a fatal error at the force cast `!`

**Comment by arbitur** [comment]
Its weird because when parsing a json string to Dictionary using JSONSerializer it works, but when passing a Dictionary literal it fails.

```swift
struct Paid: Decodable {
	let isPaid: Bool
	init?(json: JSON) {
		isPaid = ("paid" <~~ json)!
	}
}

let json = "{\"paid\": 1}"
let dict = try! JSONSerialization.jsonObject(with: Data(json)!, options: []) as! [String: Any]
let p = Paid(json: dict)! // Works
print("p:", p.isPaid) // p: true
		
let p2 = Paid(json: ["paid": 1])! // Crashes
print("p2:", p2.isPaid)
```
