### ISSUE TITLE
[GLOSS] Value found for key "image" but decoding failed.

### ISSUE THREAD

**Issue by haiderashfaq** [hkellaway/Gloss#288]
Does anyone know what this means? receiving this error in xcode log after upgrading to swift3 and xcode 8.3 :/ 

Any help would be most certainly appreciated as I cannot run my app at the moment

Thanks

**Comment by hkellaway** [comment]
it means a value was found in the JSON for the `image` key but could not be transformed into a value

https://github.com/hkellaway/Gloss/pull/277

**Comment by haiderashfaq** [comment]
@hkellaway , do you know the fix? it worked before with the <~~ operator (before swift3 upgrade)

**Comment by hkellaway** [comment]
can you provide the JSON and your Gloss model

**Comment by haiderashfaq** [comment]
@hkellaway  

final class Product: Glossy, Equatable {
    fileprivate (set) var id: Dynamic<Int> = Dynamic(0)
    fileprivate (set) var name: Dynamic<String> = Dynamic("")
    fileprivate (set) var wasPrice: Dynamic<NSDecimalNumber> = Dynamic(NSDecimalNumber())
    fileprivate (set) var price: Dynamic<NSDecimalNumber> = Dynamic(NSDecimalNumber())
    fileprivate (set) var reviewAverage: Dynamic<Float> = Dynamic(0)
    fileprivate (set) var reviewCount: Dynamic<Int> = Dynamic(0)
    fileprivate (set) var image: Dynamic<URL> = Dynamic(NSURLComponents().url!)
    fileprivate (set) var isFavorite: Dynamic<Bool> = Dynamic(false)
    
    init(id: Int, name: String, wasPrice: NSDecimalNumber, price: NSDecimalNumber,
        reviewAverage: Float, reviewCount: Int, image: URL, isFavorite: Bool = false) {
            self.id = Dynamic(id)
            self.name = Dynamic(name)
            self.wasPrice = Dynamic(wasPrice)
            self.price = Dynamic(price)
            self.reviewAverage = Dynamic(reviewAverage)
            self.reviewCount = Dynamic(reviewCount)
            self.image = Dynamic(image)
    }
    
    required init?(json: JSON) {
         print("PROD HERE")
        guard let id: Int = ("id" <~~ json),
            let name: String = ("name" <~~ json),
            let reviewAverage: Float = ("reviewAverage" <~~ json),
            let reviewCount: Int = ("reviewCount" <~~ json),
            let image: NSURL = ("image" <~~ json),
            let wasPrice = Decoder.decodeNSDecimalNumber("wasPrice")(json),
            let price = Decoder.decodeNSDecimalNumber("price")(json)
        else {
            return nil
        }
        
        self.id = Dynamic(id)
        self.name = Dynamic(name)
        self.wasPrice = Dynamic(wasPrice)
        self.price = Dynamic(price)
        self.reviewAverage = Dynamic(reviewAverage)
        self.reviewCount = Dynamic(reviewCount)
        self.image.value = Dynamic(image as URL).value
    }
    
    func toJSON() -> JSON? {
        return jsonify([
            "id" ~~> self.id.value,
            "name" ~~> self.name.value,
            Encoder.encodeNSDecimalNumber("wasPrice")(self.wasPrice.value),
            Encoder.encodeNSDecimalNumber("price")(self.price.value),
            "reviewAverage" ~~> self.reviewAverage.value,
            "reviewCount" ~~> self.reviewCount.value,
            "image" ~~> self.image.value])
    }
}

func ==(lhs: Product, rhs: Product) -> Bool {
    if lhs.id.value != rhs.id.value {
        return false
    }
    
    if lhs.reviewCount.value != rhs.reviewCount.value {
        return false
    }
    
    if lhs.name.value.compare(rhs.name.value) != ComparisonResult.orderedSame {
        return false
    }
    
    if lhs.wasPrice.value.compare(rhs.wasPrice.value) != ComparisonResult.orderedSame {
        return false
    }
    
    if lhs.price.value.compare(rhs.price.value) != ComparisonResult.orderedSame {
        return false
    }
    
    if fabs(lhs.reviewAverage.value - rhs.reviewAverage.value) > Constants.FloatingPointMinimumAccuracy {
        return false
    }
    
    if lhs.image.value.absoluteString.compare(rhs.image.value.absoluteString) != .orderedSame {
        return false
    }
    
    if lhs.isFavorite.value != rhs.isFavorite.value {
        return false
    }
    
    return true
}

**Comment by haiderashfaq** [comment]
@hkellaway Please see below:
```SWIFT
final class Product: Glossy, Equatable {
    fileprivate (set) var id: Dynamic<Int> = Dynamic(0)
    fileprivate (set) var name: Dynamic<String> = Dynamic("")
    fileprivate (set) var wasPrice: Dynamic<NSDecimalNumber> = Dynamic(NSDecimalNumber())
    fileprivate (set) var price: Dynamic<NSDecimalNumber> = Dynamic(NSDecimalNumber())
    fileprivate (set) var reviewAverage: Dynamic<Float> = Dynamic(0)
    fileprivate (set) var reviewCount: Dynamic<Int> = Dynamic(0)
    fileprivate (set) var image: Dynamic<URL> = Dynamic(NSURLComponents().url!)
    fileprivate (set) var isFavorite: Dynamic<Bool> = Dynamic(false)
    
    init(id: Int, name: String, wasPrice: NSDecimalNumber, price: NSDecimalNumber,
        reviewAverage: Float, reviewCount: Int, image: URL, isFavorite: Bool = false) {
            self.id = Dynamic(id)
            self.name = Dynamic(name)
            self.wasPrice = Dynamic(wasPrice)
            self.price = Dynamic(price)
            self.reviewAverage = Dynamic(reviewAverage)
            self.reviewCount = Dynamic(reviewCount)
            self.image = Dynamic(image)
    }
    
    required init?(json: JSON) {
         print("PROD HERE")
        guard let id: Int = ("id" <~~ json),
            let name: String = ("name" <~~ json),
            let reviewAverage: Float = ("reviewAverage" <~~ json),
            let reviewCount: Int = ("reviewCount" <~~ json),
            let image: NSURL = ("image" <~~ json),
            let wasPrice = Decoder.decodeNSDecimalNumber("wasPrice")(json),
            let price = Decoder.decodeNSDecimalNumber("price")(json)
        else {
            return nil
        }
        
        self.id = Dynamic(id)
        self.name = Dynamic(name)
        self.wasPrice = Dynamic(wasPrice)
        self.price = Dynamic(price)
        self.reviewAverage = Dynamic(reviewAverage)
        self.reviewCount = Dynamic(reviewCount)
        self.image.value = Dynamic(image as URL).value
    }
    
    func toJSON() -> JSON? {
        return jsonify([
            "id" ~~> self.id.value,
            "name" ~~> self.name.value,
            Encoder.encodeNSDecimalNumber("wasPrice")(self.wasPrice.value),
            Encoder.encodeNSDecimalNumber("price")(self.price.value),
            "reviewAverage" ~~> self.reviewAverage.value,
            "reviewCount" ~~> self.reviewCount.value,
            "image" ~~> self.image.value])
    }
}

func ==(lhs: Product, rhs: Product) -> Bool {
    if lhs.id.value != rhs.id.value {
        return false
    }
    
    if lhs.reviewCount.value != rhs.reviewCount.value {
        return false
    }
    
    if lhs.name.value.compare(rhs.name.value) != ComparisonResult.orderedSame {
        return false
    }
    
    if lhs.wasPrice.value.compare(rhs.wasPrice.value) != ComparisonResult.orderedSame {
        return false
    }
    
    if lhs.price.value.compare(rhs.price.value) != ComparisonResult.orderedSame {
        return false
    }
    
    if fabs(lhs.reviewAverage.value - rhs.reviewAverage.value) > Constants.FloatingPointMinimumAccuracy {
        return false
    }
    
    if lhs.image.value.absoluteString.compare(rhs.image.value.absoluteString) != .orderedSame {
        return false
    }
    
    if lhs.isFavorite.value != rhs.isFavorite.value {
        return false
    }
    
    return true
}
```

**Comment by hkellaway** [comment]
the json?

**Comment by haiderashfaq** [comment]
@hkellaway hold on, i am noticing some very strange behaviour with my json and from which api call its coming from. Let me get back you asap please. Thanks

**Comment by haiderashfaq** [comment]
@hkellaway json response is as follows:

```
PROD HERE: ["reviewCount": 13, "name": Olixar Ultra-Thin iPhone 7 Plus Gel Case - Crystal Clear, "id": 59815, "image": http://images.mobilefun.co.uk/graphics/450pixelp/60911.jpg, "reviewAverage": 4.6, "price": 7.99, "mf_sort_priority": 12, "wasPrice": 0]
```

**Comment by haiderashfaq** [comment]
```
PROD HERE: ["reviewCount": 13, "name": product1, "id": 515, "image": http://images.example.jpg, "reviewAverage": 4.6, "price": 7.99, "mf_sort_priority": 12, "wasPrice": 0]
```

@hkellaway

**Comment by hkellaway** [comment]
the issues is with this line: `let image: NSURL = ("image" <~~ json)`

Gloss doesn't have decoding for `NSURL` - only `URL`.  if you can change that to `URL`, it should work fine - otherwise do your own transformation (https://github.com/hkellaway/Gloss#custom-transformations)

**Comment by haiderashfaq** [comment]
@hkellaway thanks mate
