### ISSUE TITLE
Make it possible to parse any valid JSON, not just [key: AnyObject?]

### ISSUE THREAD

**Issue by chefren** [hkellaway/Gloss#289]
Hi,
As per the json [definition](http://json.org/) a json array can have any value. I tried the following and cannot decode
```
struct Testy : Decodable {
    let array : JSON
    init?(json: JSON){
        self.array = json
    }
}
```

```
        let myTestJSONString = "[\"justString\",{\"k1\":1}]"  // Valid JSON
        let myJson = Testy(data: myTestJSONString.data(using: .utf8)!)
        print("My test: \(String(describing: myJson?.array.description))")

```

and it prints: "nil"

Is this perhaps just not in the documentation but still possible to do with the current version?

Thanks!

**Comment by chefren** [comment]
Hi @hkellaway , do you have any answer? Why was this closed?

**Comment by hkellaway** [comment]
this was closed due to lack of activity

myself, im not doing additional implementation for Gloss rather supporting in maintenance mode - my recommendation is to use Codable

if anyone would like to submit a pull request for this complete with tests, im happy to review
