### ISSUE TITLE
Kitura Compatibility: Converting to Numeric Types from String's

### ISSUE THREAD

**Issue by crspybits** [hkellaway/Gloss#291]
We talked about this before Harlan, but I wanted to note where this issue was coming up for me. And an ensuing concern.

Previously, I mentioned I had a need to convert from strings to numeric values in my decoding (see https://github.com/hkellaway/Gloss/issues/268). We discussed this and decided at the time that decoding a number from a string might be considered an error or special case. The standard for json integers is to not have them quoted. E.g., {"intvalue": 1}. See also http://www.json.org.

I looked through my code to see where this was coming up and it turns out that it crops up due to my use of Kitura to provide HTTP support for my server. In this, Kitura has a `RouterRequest` object and this object has a method `queryParameters`. `queryParameters` provides, in dictionary form, the parameters from the incoming HTTP request present in the URL. All of the values for the keys in the query are provided as strings. For example if the query was http://foobar.com/?key=100, then the resulting dictionary from `queryParameters` would be ["key": "100"]. 

Since Kitura is a pretty common library to use when developing servers using Swift, I wanted to raise my previous issue as a concern again. It seems like we should have Gloss support commonly used server-side use cases. It also looks like Vapor, another popular server side framework, does something similar (see https://vapor.github.io/documentation/http/request.html).

**Comment by ryanschneider** [comment]
If this is implemented, it needs to be implemented for every "numeric" type Gloss supports, so Int, Double, Float, Decimal, etc.

That is to say you might want to serialize your `["key": "100"]` example to:

```swift
struct QueryParams {
   let key: Int
}
```

But I might want to serialize it to:

```swift
struct QueryParams {
   let key: Double?
}
```

But personally, I think this String -> Type conversion would be something better handled inside Kitura/Vapor/etc.  It looks like Vapor at least already does that with SwiftyJSON style `.int` extensions.  Also it looks like SwiftyJSON is vendored inside Kitura releases anyways.  

I think SwiftyJSON is the framework focused on manipulating "untyped" JSON, Gloss is really for JSON <-> struct serialization, IMO adding edge cases to handle malformed JSON sounds like a dangerous path.

And besides, HTTP query parameters aren't really JSON to begin with.  Don't forget that `?key=100&key=101&key=Foo` is a valid query parameter in a URL.  Lots of server frameworks in other languages would map to to something like '["key": [100, 101, "Foo"]]'.  My point is that even if this code was added to Gloss it still sounds like there are additional situations that need to be handle upstream and/or in your code.

**Comment by crspybits** [comment]
Interesting. Perhaps I'm using Gloss for something it's not intended for. But, perhaps something could be clarified in the Gloss documentation. Gloss converts between objects and the `JSON` type which is a Swift dictionary. I usually think of JSON as being either in string format or in actual Javascript, not as Swift dictionaries. I agree that HTTP query parameters are not JSON-like. Swift dictionaries are more JSON-like, but are they JSON?

In any event, for me right now, without this numeric <-> string conversion it costs me specifically is a little less clarity in my model conversion code. I can't use the nice "~~>" style operators in some cases, and have to do things like:

        self.fileVersion = Decoder.decode(int32ForKey: UploadFileRequest.fileVersionKey)(json)

Plus, of course, I have to have an additional Decoder implementation to support this.

So, this raises a slightly different question: Is there a way I could use the "~~>" style notation and "plugin" my feature of numeric <-> string conversion? Does that make sense?

**Comment by ryanschneider** [comment]
Can't you do?

```swift
if let f: String = "key" <~~ json {
    self.fileVersion = Int32(f)
}
else {
    self.fileVersion = nil
}
```

Or replace the `if let` with some `!` if fileVersion is `Int32` rather than `Int32?`.

Which brings up another good point: these built-in methods would need to return `T?` since the string might not be parseable so you'd still need to handle that. 

You could write your own ~~> function to convert a String to Int? but IMO this shouldn't be something exported by default from Gloss since it'll hurt far more people than it'll help (I'd be mad if I accidentally passed Gloss a string when I typoed an input to a to an Int and it led to runtime issues rather than a failure to compile).  At the very least I'd want it to be a different op like -!> so it's obvious it's doing something non standard, but if I recall correctly Harlan has said he's opposed to adding more ops since it complicates learning the framework.
