### ISSUE TITLE
From swift 2.3 to 3.0 - Each of my Struct saying " " does not conform to protocol 'Decodable' or 'Encodable'

### ISSUE THREAD

**Issue by vandanakanwar** [hkellaway/Gloss#292]
Hi @hkellaway ,
My code was working fine when I was using Gloss - 0.8.0 Version for my swift 2.3 project. Now I am converting my code to swift 3.0 and I am using Gloss version 1.0.0.
In each model class, I am getting does not conform to the protocol.

*****Sample Code*****

`
import Gloss
struct myRequest: Encodable, CustomDebugStringConvertible {

    let first: String
    let second: Bool
    let third: Double
    var debugDescription: String {
        return "~myRequest~"
    }

    init(first: String, second: Bool = false, third: Double) {
        self.first = first
        self.second = second
        self.third = third

    }

    func toJSON() -> JSON? {
        return jsonify([
                "first" ~~> self.first,
                "second" ~~> self.second,
                "third" ~~> self.third,
        ])
    }
}

`

Am I doing something wrong?
Need help @hkellaway

**Comment by hkellaway** [comment]
i copy/pasted your model there using the latest Gloss version as well as the version you say you're using (`1.0.0`) and i am not getting any message about not conforming to a protocol, sorry.

usually Xcode will help you out by allowing you to insert whatever function it is you're missing.

**Comment by vandanakanwar** [comment]
Hi @hkellaway 
Actually, In my project, I was also using public typealias **JSON** = [String: AnyObject],
which was creating a problem because in Gloss same name type alias is used.
But compiler was giving me an error regarding protocol compliance. That was quite weird.

Thanks for your quick reply.
I am closing this issue.
