### ISSUE TITLE
Parsing a JSON Object with array of objects

### ISSUE THREAD

**Issue by humayunharoon** [hkellaway/Gloss#293]
Hey! I have a JSON object like this, lets call it Album, for which there is a Album gloss model.
```
"id":"xxx-xxx-xxx-xxx",
"type":"home",
"pictures":[
{
"id":32,
"classification":"sharp",
"url":"https://xxx.com"
}
]
```

I've created the picture object as a Gloss model as well. Is there no way to auto populate the array of pictures inside the Album gloss model?

EDIT: Nvm it seems it just works automatically by pointing the JSON array to the object array, inside another object. If this was documented, that would've been really handy.

Shall i give it a go?

**Comment by hkellaway** [comment]
im not quite sure what you're asking for. you mean documentation on the fact that if one of your properties is an array of Gloss models it will be handled? all the types Gloss handles are listed, including arrays: https://github.com/hkellaway/Gloss#on-using-gloss-operators
