### ISSUE TITLE
[Gloss] Value found for key "id" but decoding failed

### ISSUE THREAD

**Issue by Bathibabu** [hkellaway/Gloss#297]
I am sharing my json response here.i am getting "[Gloss] Value found for key "id" but decoding failed" following warning and id is not storing in model.I am using gloss version 1.2.4
```
▿ 0 : 2 elements
    - .0 : "is_verified"
    - .1 : 0
  ▿ 1 : 2 elements
    - .0 : "data"
    ▿ .1 : 2 elements
      ▿ 0 : 2 elements
        - .0 : id
        - .1 : 32
      ▿ 1 : 2 elements
        - .0 : phone_number
        - .1 : +xx-xxxxxxxxxx
  ▿ 2 : 2 elements
    - .0 : "message"
    - .1 : OTP is sent to your phone to verify your account
```

My model is:
------------
```
class UserInfoResponse: Decodable {

    var Data : UserInfo?
    var Token : String?
    var otpVerified : Int?
    required init?(json: JSON) {
        
        Data = "data" <~~ json
        Token = "auth_token" <~~ json
        otpVerified = "is_verified" <~~ json
    }
}
class UserInfo : Decodable {

    var Id : Int?
    required init?(json: JSON) {
        
        guard let myId: Int = "id" <~~ json else {
            return nil
        }
        Id    = myId
    }
    }   
}
```

**Comment by hkellaway** [comment]
can yo provide the JSON itself, not what's printed in the console

**Comment by hujunfeng** [comment]
Run into the same error in Xcode 9 beta 2. It looks like that Gloss could not decode a value if the property is type of `Float`.

Here is example:

```swift
// Model
struct MyStruct: Gloss.Decodable {
    var floatValue: Float
    
    public init?(json: JSON) {
        guard let floatValue: Float = "floatValue" <~~ json else { return nil }
        self.floatValue = floatValue
    }    
}

// Using the following example to decode
let exampleJSON: JSON = [
    "floatValue" : 1.23,
]
        
guard let device = MyStruct(json: exampleJSON) else {
    print("DECODING FAILURE :(")
    return
}
```

It would fail in Xcode 9 with the following error:
```
[Gloss] Value found for key "floatValue" but decoding failed.
DECODING FAILURE :(
```

It might be related to the changes of NSNumber in iOS 11 and macOS 10.13:
> Bridging NSNumbers in swift to numeric types now uniformly limits the cases of as? cast no matter how the NSNumber was created. Casting NSNumbers to numeric types will return nil if the number cannot be safely represented as the target type.
[Foundation Release Notes](https://developer.apple.com/library/content/releasenotes/Foundation/RN-Foundation/index.html)


Here is what I found in debugger:
![2017-06-26 at 3 05 am](https://user-images.githubusercontent.com/158831/27518892-552aacec-5a1c-11e7-9f49-03e82fd0f2a9.png)

**Comment by Bathibabu** [comment]
{
  "message": "OTP is sent to your phone to verify your account",
  "auth_token": "",
  "data": {
    "id": "12",
    "phone_number": "+91-XXXXXXXXXX"
  },
  "is_verified": 0
}

**Comment by hkellaway** [comment]
with these models:

```struct MyObject: Decodable {
    
    let message: String
    let authToken: String
    let data: MyData
    let isVerified: Bool
    
    init?(json: JSON) {
        guard
            let message: String = "message" <~~ json,
            let authToken: String = "auth_token" <~~ json,
            let data: MyData = "data" <~~ json,
            let isVerifiedNum: Int = "is_verified" <~~ json
            else {
            return nil
        }
        
        self.message = message
        self.authToken = authToken
        self.data = data
        self.isVerified = (isVerifiedNum == 1) ? true : false
    }
    
}

struct MyData: Decodable {
    
    let id: String
    let phoneNumber: String
    
    init?(json: JSON) {
        guard
            let id: String = "id" <~~ json,
            let phoneNumber: String = "phone_number" <~~ json else {
                return nil
        }
        
        self.id = id
        self.phoneNumber = phoneNumber
    }
    
}```

this works as expected:

```
        let json: JSON = [
            "message" : "OTP is sent to your phone to verify your account",
            "auth_token" : "",
            "data" : [
                "id" : "12",
                "phone_number" : "+91-XXXXXXXXXX"
            ],
            "is_verified" : 0
        ]
        
        guard let myObj = MyObject(json: json) else {
            print("DECODING FAILURE :(")
            return
        }
        
        print(myObj)
```

**Comment by Bathibabu** [comment]
Thank you, It is working fine
