### ISSUE TITLE
Documentation/README suggestion update

### ISSUE THREAD

**Issue by xaphod** [hkellaway/Gloss#298]
It would have saved me 30-60 minutes if you could have mentioned that to from your `JSON` object to Data, you need something like `try? JSONSerialization.data(withJSONObject: json, options: [])`, and to go from Data to your JSON object you need something like `try? JSONSerialization.jsonObject(with: jsonData, options: [])`

FYI, I can't use your `data` convenience function. It doesn't go both ways, and it spits out nil for me always.

**Comment by hkellaway** [comment]
would you be able to submit a PR with the suggested update to documentation?

and for the data convenience function can you file a separate Issue and include the JSON and your model(s)

**Comment by xaphod** [comment]
Sure i'll try to get to it this week.
