### ISSUE TITLE
Consider Adding Default Value In Decoder.decode(enumArrayForKey:)

### ISSUE THREAD

**Issue by Blackjacx** [hkellaway/Gloss#299]
I try to map a JSON to an array of enums for which I know all cases today. But the cases can grow in number in the future. With your implementation of `Decoder.decode(enumArrayForKey:)` it will break the mapping in future when the backend guys add more cases and an unknown case finds its way in the JSON. 

I need a functionality that parses all cases that are `known` in the resulting array. Cases that are unknown should be left out or replaced by a `default value.

Currently you just return nil when you find ONE case that is not supported and you ignore all other cases that can be mapped eventually. I would suggest du replace the line https://github.com/hkellaway/Gloss/blob/b74479da70128ef17cfb1440108ca85e7ee4189e/Sources/Decoder.swift#L274 by `continue` and add the optional defaultValue if it can be unwrapped.

The following solutions strips unknown cases:
```
func decodeMyEnum(key: String, json: JSON) -> [MyEnum] {

    let raw = (json.valueForKeyPath(keyPath: key) as? [String])
    let values = raw?.flatMap { MyEnum(rawValue: $0) } ?? []
    return values
}
```

This in generic would be awesome 🙃

**Comment by hkellaway** [comment]
For all types, Gloss returns `nil` in the case there was an issue parsing the indicated value
 (see https://github.com/hkellaway/Gloss/issues/189). Changing this just for enum arrays would make the behavior different in only this one case

If a different behavior is needed specific to your application, you can create custom functions like the one indicated

**Comment by Blackjacx** [comment]
YES that’s true but I can partially initialize my objectors and this that should be possible for meins too. You wouldn’t break anything if you’d provide a optional default value so everybody can feel free to throw in an .unknown value as default that is set for the unknown cases. If it is not provided ( the default ) the user will get the same behavior as today.

I understand that you want to keep everything consistent. But I didn’t expect that I don’t receive any enum case, even not the ones I know.

**Comment by hkellaway** [comment]
reading this is seems like one would always get an array of values or an empty array - and to maintain the same behavior as today, it would have to return `nil`, not an empty array

can you provide an example of the usages you're referring to - one with a default and one without? i'm not sure i fully understand

**Comment by Blackjacx** [comment]
Concretely I mean the following:

import Foundation

// JSON:
// {
//     "cases": ["first", "third"]
// }

enum MyEnum: String {
    case unknown
    case first
    case second
}

public static func decode<T: RawRepresentable>(enumArrayForKey key: String, keyPathDelimiter: String = GlossKeyPathDelimiter, defaultValue: T? = nil) -> (JSON) -> [T]? {
    return { json in

        if let rawValues = json.valueForKeyPath(keyPath: key, withDelimiter: keyPathDelimiter) as? [T.RawValue] {
            var enumValues: [T] = []

            for rawValue in rawValues {
                guard let enumValue = T(rawValue: rawValue) else {
                    guard let defaultValue = defaultValue else {
                        return nil
                    }
                    enumValues.append(defaultValue)
                    continue
                }
                enumValues.append(enumValue)
            }
            return enumValues
        }
        return nil
    }
}

// Will result in an array returned which will contain known cases and the default value for all cases that could not be parsed, i.e. are unknown.
let parsedCasesWithDefaultValue = Gloss.Decoder.decode(enumForKey: "key", defaultValue: .unknown)(json)

// Will represent the current behaviour, i.e. returning nil when one case is unknown
let parsedCasesWithoutDefaultValue = Gloss.Decoder.decode(enumForKey: "key")(json)

This way you can support both behaviours. Does this make sense?

**Comment by hkellaway** [comment]
ah yes, i see what you're saying - that's neat. should probably have the same functionality for just an enum as well as the array variety

would you be able to create a PR with that functionality along with tests?

**Comment by Blackjacx** [comment]
Apparently I have currently no time for this. As you said I simply have written my own function for this.
