### ISSUE TITLE
Serialization

### ISSUE THREAD

**Issue by usamabinattique** [hkellaway/Gloss#300]
Hi, I am a newbie to swift and i came across your library which is really awesome i must say but i am having a little issue with trying to post data. I am defining a struct like mentioned in the examples

    struct UserData : Glossy {
    
    var firstName : String?
    var email : String?
    var lastName : String?
    var password : String?

    init(json: JSON) {   
        self.firstName = "firstName" <~~ json
        self.lastName = "lastName" <~~ json
        self.email = "email" <~~ json
        self.password = "password" <~~ json  
    }
    func toJSON() -> JSON? {
        return jsonify([
            "firstName" ~~> self.firstName,
            "lastName" ~~> self.lastName,
            "email" ~~> self.email,
            "password" ~~> self.password,
            ])
    }    
  }
I am creating a generic funtion for the request like this as 

       func createURLRequest(urlString: String, postData: String, isAuthenticatedRequest: Bool) -> URLRequest {
        
        
        let urlStr = "http://abc.xyz.com/"
        let combinedUrlString = urlStr + urlString
        let url = URL(string: combinedUrlString)
        let request =  NSMutableURLRequest()
        request.url = url
        request.allHTTPHeaderFields = ["Accept" : "application/json"]
        if isAuthenticatedRequest {
            request.allHTTPHeaderFields = ["token_type" : "bearer"]
        } 
        if postData.characters.count > 0 {
            request.httpMethod = "POST"
        }
        else {
            request.httpMethod = "GET"
        }
       return request as URLRequest
        
    }

and below is the func where i am trying to post data 

       func userLogin() {
    
    let request = self.createURLRequest(urlString: GenericConstants.serviceURLs().register, postData:"" , isAuthenticatedRequest: false)
    
    let session = URLSession.shared
    let task = session.dataTask(with: request) { (data, urlResponse, error) in
    
        if (error != nil) {
            //we got error from service
            self.getUserLoginInFailed(GenericConstants.AlertStrings().somethingWentWrong)
        } else if let httpResponse = urlResponse as? HTTPURLResponse {
           
            if httpResponse.statusCode != 200 {
             self.getUserLoginInFailed(GenericConstants.AlertStrings().somethingWentWrong)
            } else {
                //chcek if json is valid and does not contain error key
                let jsonString = String(data: data!, encoding:String.Encoding.utf8)
                if(jsonString!.characters.count == 0){
                    //json is not valid
                    //show error message
                    self.getUserLoginInFailed(GenericConstants.AlertStrings().somethingWentWrong)
                }
                else {
                   // here when i call let body = UserData.toJSON("code")
                   it asks for an argument and even if i try to pass a variable which holds key pair values 
                 it still gives me an error like Instance member toJSON cannot be used on 'UserData'. 
                   Did you mean to use a value of this type instead? what am i doing wrong and what do i 
                need to pass to post data on the url and how would i make this call. please help
                    
                }
            }
        }
    }
    task.resume()  
    }

**Comment by hkellaway** [comment]
Calling UserData.toJSON() implies toJSON() is a static function on UserData. what you need is an instance of UserData to POST.

i.e. 
let myUserData = UserData(firstName: "Usama", email: "a@b.com", lastName: "Bin Attique", password: "Abc123")
let json = myUserData.toJSON()

here, myUserData is an instance of UserData
