### ISSUE TITLE
Decoder is ambiguous for type lookup in this context

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [hkellaway/Gloss#301]
I get the above error where I'm extending `Decoder`.

```swift
extension Decoder { // 'Decoder' is ambiguous for type lookup in this context

}
```

I'm using Xcode 9 beta 4 so I understand that this has something to do with Swift 4. A naming conflict perhaps?

Any quick fix for this? I have the library installed via CocoaPods so I can't edit the source there.

**Comment by hkellaway** [comment]
try using the explicit namespace - Gloss.Decoder

**Comment by Isuru-Nanayakkara** [comment]
That works!

**Comment by hkellaway** [comment]
naming will be updated to `JSONDecodable` and `JSONEncodable` as of version `2.0.0-beta.2`

**Comment by Sihak** [comment]
Gloss.Decodable
