### ISSUE TITLE
Fail to compile in Swift4 Xcode9b4 -  'init()' is internal and cannot be referenced

### ISSUE THREAD

**Issue by jannejava** [hkellaway/Gloss#302]
First of all, great work! This excellent library worked very well for me. But now I am updating my apps to Swift4 (Xcode9b4) and suddenly have some errors.

```
ExtensionArray.swift:76:63: Initializer 'init()' is internal and cannot be referenced from a default argument value

ExtensionDecodable.swift:38:52: Initializer 'init()' is internal and cannot be referenced from a default argument value
```

I did download the swift_4-branch with no success.

**Comment by rbukovansky** [comment]
Are those errors from building your app or from building Gloss?

I'm able to build Gloss from `swift_4.0` branch using `swift build && swift test` normally (tests fail, but I have created PR #303 to have them pass). It's also "buildable" on Travis as you can see here: https://travis-ci.org/rbukovansky/Gloss/jobs/260950618

**Comment by jannejava** [comment]
Thanks for your reply! It's coming from `ExtensionArray.swift` and `ExtensionDecodable.swift` found inside the Gloss project. 

The project is it self a just migrated from Swift 3 to Swift 4.

I created a new fresh project with Gloss swift_4 and it does indeed compile but not my migrated project. I don't know if it's Xcode9-beta is pulling my legs. Cannot understand why it should be different?

![screenshot-2017-08-04 14-02-pxf8n](https://user-images.githubusercontent.com/543616/28967883-a19ed0c4-791d-11e7-92c9-e146544ed9a4.png)

**Comment by hkellaway** [comment]
from the sound of the error message it's that a public initializer needs to be added to GlossJSONSerializer as such:

public init() { }

can you try making that change to the pod locally and seeing if it fixes the issue?

**Comment by jannejava** [comment]
Ah, that's it! Seems to compile just fine now.

**Comment by jannejava** [comment]
Needed to add `public init() { }` in `GlossLogger` as well. The app is now running.

**Comment by hkellaway** [comment]
I'll update the swift_4.0 branch accordingly. thanks!

**Comment by hkellaway** [comment]
@jannejava merged - you can now work off branch `swift_4.0`
