### ISSUE TITLE
Strategies to decode / encode across different styles?

### ISSUE THREAD

**Issue by dhushon** [hkellaway/Gloss#310]
All,  
Quick question - hopefully..

Traditional structure based decodes via <~~ json are very powerful
To do this we create extension structures and that's fine.
This works well for 1:1 cardnality problems, but I have a m:n problem...
I need to be able to read multiple json structured streams, normalize them and then re-encode in a differential JSON structure.... 

Simple things like moving from x, width, h, height to xmin, xmax, ymin, ymax as well as some value addition/removal... 

The struct is normalizable, but encoding and decoding strategies do not allow me to pull a "decode or encode" option at this point... I'd love to have an init?(json: JSON, option: Any) model.  Outside a fork, is there an easy way to solve?

thanks,

/dan

**Comment by hkellaway** [comment]
i'm genuinely not sure if there's a way to solve that problem with the current implementation as im not 100% sure what you're describing. if you could provide a concrete example, that might help. also not clear on what a general-purpose `init?(json: JSON, option: Any)` would be for. 

as you've gathered, the library is quite straight forward - given a type, it'll try to decode/encode and be a little smart about arrays and dictionaries.

**Comment by dhushon** [comment]
Just picked it up... I just have to overwrite the Encodable / Decodable protocols, e.g.

public init?(json: JSON, option: option) {
        // decode option
        self.init(json:json)
    }
    
    public init?(json: JSON) {
       // do selected parsing
      switch(option): 
           case optionA:
           case optionB:
   }
}

I believe... thanks for the quick response!

**Comment by hkellaway** [comment]
cool. works for your use case?

**Comment by dhushon** [comment]
will let you know in a few...
