### ISSUE TITLE
Crash after build

### ISSUE THREAD

**Issue by ArjunPatel011** [hkellaway/Gloss#314]
Hi , I am using   **pod 'Gloss', '~> 0.7.4'**  version in Swift 2.3 . My issue is App is crash when make a build otherwise its work perfect in simulator also in debugger mode. here is my fabric log. please guide.

Crashed: com.apple.main-thread
0  Gloss                          0x101b6e718 specialized specialized Dictionary.setValue(valueToSet : Any, forKeyPath : String, withDelimiter : String) -> () (ExtensionDictionary.swift:153)
1  Gloss                          0x101b71e94 jsonify([[String : AnyObject]?], keyPathDelimiter : String) -> [String : AnyObject]? (Gloss.swift)
2  Fiyre                          0x1003edd1c AddMeasurment.toJSON() -> [String : AnyObject]? (AddMeasurment.swift:78)
3  Fiyre                          0x1005ff3c0 specialized addMeasurmentAssistedViewController1.btnDone(AnyObject) -> () (addMeasurmentAssistedViewController1.swift:175)
4  Fiyre                          0x1005fc790 @objc addMeasurmentAssistedViewController1.btnDone(AnyObject) -> () (addMeasurmentAssistedViewController1.swift)
5  UIKit                          0x18ed71614 -[UIApplication sendAction:to:from:forEvent:] + 96
6  UIKit                          0x18ed71594 -[UIControl sendAction:to:forEvent:] + 80
7  UIKit                          0x18ed5c2fc -[UIControl _sendActionsForEvents:withEvent:] + 440
8  UIKit                          0x18ed70e88 -[UIControl touchesEnded:withEvent:] + 576
9  UIKit                          0x18ed709a8 -[UIWindow _sendTouchesForEvent:] + 2544
10 UIKit                          0x18ed6be78 -[UIWindow sendEvent:] + 3208
11 UIKit                          0x18ed3d384 -[UIApplication sendEvent:] + 340
12 UIKit                          0x18f68a85c __dispatchPreprocessedEventFromEventQueue + 2364
13 UIKit                          0x18f68cde8 __handleEventQueueInternal + 4760
14 UIKit                          0x18f685d04 __handleHIDEventFetcherDrain + 152
15 CoreFoundation                 0x1858ae2e8 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 24
16 CoreFoundation                 0x1858ae268 __CFRunLoopDoSource0 + 88
17 CoreFoundation                 0x1858adaf0 __CFRunLoopDoSources0 + 204
18 CoreFoundation                 0x1858ab6c8 __CFRunLoopRun + 1048
19 CoreFoundation                 0x1857cbfb8 CFRunLoopRunSpecific + 436
20 GraphicsServices               0x187663f84 GSEventRunModal + 100
21 UIKit                          0x18eda02f4 UIApplicationMain + 208
22 Fiyre                          0x100414760 main (AppDelegate.swift:29)
23 libdyld.dylib                  0x1852ee56c start + 4

**Comment by hkellaway** [comment]
im not certain the issue. if you’re using nested key paths that was causing a crash in certain versions including 0.7.4 (https://github.com/hkellaway/Gloss/issues/135). that feature was removed in 0.8.0. if that’s your issue, perhaps try removing nested key paths and using 0.8.0 or turning off optimization

im no longer actively supporting Swift 2.x fyi
