### ISSUE TITLE
Encode and return an array instead of a dictionary

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [hkellaway/Gloss#315]
I have this simple struct.

```swift
public struct Skill {
    public let id: String
    public let name: String
}
```

I'm sending an array of skills [Skill] to an API. In this array, I need to only send the `id`s. Like so.

```
[
    "001andjdgsd",
    "002rusnfkas",
    "003fioasmfk"
]
```

The `toJSON()` method in `JSONEncodable` protocol return a dictionary. Which is not usable in this case.

Is there a way to just return the `id` value as a string?

**Comment by hkellaway** [comment]
no, `toJSON()` is intended to produce a JSON dictionary.

you could create a function custom to your application to map over your `Skill`s and gets the `id`s instead of attempting to use the `toJSON()` function
