### ISSUE TITLE
Xcode gets stuck on compiling gloss. I suspect some kind of type inference 

### ISSUE THREAD

**Issue by MANassar** [hkellaway/Gloss#317]
<img width="710" alt="screen shot 2017-12-14 at 11 22 22" src="https://user-images.githubusercontent.com/1597951/33987440-28fec744-e0c1-11e7-8824-2d5ed2e09895.png">

This has been the case for the last hour. It is the same whether adding the source code or via Cocoapods.

**Comment by hkellaway** [comment]
ive not encountered this myself; so i'm not sure what's going on.

what version of Gloss are you using?
