### ISSUE TITLE
toJSON()

### ISSUE THREAD

**Issue by arjun011** [hkellaway/Gloss#318]
![screen shot 2017-12-28 at 5 09 13 pm](https://user-images.githubusercontent.com/16661905/34411494-f4d7733e-ebfc-11e7-9f14-cba8766019c3.png)

[net.jiniguru.me_issue_42_crash_d3d31fa38f494bb8a4671cb4c734180e_36f6ce82ebbd11e790f156847afe9799_0_v2.txt](https://github.com/hkellaway/Gloss/files/1591226/net.jiniguru.me_issue_42_crash_d3d31fa38f494bb8a4671cb4c734180e_36f6ce82ebbd11e790f156847afe9799_0_v2.txt)

I am facing this issue on distribution build. not even Development and Simulator.
Whenever I was try to convert Glossy object to Dictionary (.toJSON()). I am using "  pod 'Gloss', '~> 0.7.4'" version. I couldn't update swift version for some other issue . Please help

**Comment by hkellaway** [comment]
this issue may be from you as well? https://github.com/hkellaway/Gloss/issues/314

as mentioned there, if you’re using nested key paths that was causing a crash in certain versions including 0.7.4 (#135). that feature was removed in 0.8.0. if that’s your issue, perhaps try removing nested key paths and using 0.8.0 or turning off optimization

im no longer actively supporting Swift 2.x fyi, and so am not troubleshooting further. hope that helps.
