### ISSUE TITLE
Change to change log?

### ISSUE THREAD

**Issue by crspybits** [hkellaway/Gloss#322]
Add in-- that Linux is no longer being supported? i.e., because of the Tests directory structure and the removal of Linux tests.

(I fully realize I've not been giving this any love).

**Comment by rbukovansky** [comment]
It's not. For now...
But when I finish this one project I'm currently working on, I will get to it and redo Linux support (approx. after April).
I just hope Swift language devs resolved issues I had with Swift on Linux.

**Comment by hkellaway** [comment]
sure, can mention in the next release Changelog notes that Linux isn't supported
