### ISSUE TITLE
Operators from unordered precedence groups

### ISSUE THREAD

**Issue by teeeeeegz** [hkellaway/Gloss#328]
Hey team,

I've begun working on a new project with Swift 4.1, using Gloss 2.0.0, and have the following issue appear in AppCode 2018.1, but not in Xcode 9.3.

![image](https://user-images.githubusercontent.com/9068436/39104803-5c782224-46f5-11e8-9597-014d16f2eac8.png)

![image](https://user-images.githubusercontent.com/9068436/39104814-6c72fe74-46f5-11e8-9f77-5da5c9b1e49d.png)

![image](https://user-images.githubusercontent.com/9068436/39104811-657c8824-46f5-11e8-9852-10afb92ef350.png)

This message seems to be a general warning and doesn't prevent me from compiling, but having searched the issue tracker here with nothing similar appearing I figured others might have this problem.

Cleaning and building, plus restarting AppCode didn't make a difference.

**Comment by hkellaway** [comment]
thanks for tracking that! glad to see its not a blocker. feel free to submit cosmetic changes that don't impact functionality but keep AppCode happy

 i'll take the platform though to document that i won't personally be supporting AppCode
