### ISSUE TITLE
swift package generate-xcodeproj fails

### ISSUE THREAD

**Issue by str11ngfello** [hkellaway/Gloss#330]
Hello,

I can get the swift package manager to fetch Gloss, but I cannot generate the xcode project.  When I run swift package generate-xcode, it fails with "error: package has unsupported layout; found loose source files: /"

Please see below:

Lowells-MacBook-Pro-2:PerfectTemplate lowellduke$ swift package update
Fetching https://github.com/hkellaway/Gloss.git
Updating https://github.com/PerfectlySoft/Perfect-HTTPServer.git
Updating https://github.com/PerfectlySoft/Perfect-CZlib-src.git
Updating https://github.com/PerfectlySoft/Perfect-HTTP.git
Updating https://github.com/PerfectlySoft/Perfect-Net.git
Updating https://github.com/PerfectlySoft/Perfect-Crypto.git
Updating https://github.com/PerfectlySoft/Perfect-Thread.git
Updating https://github.com/PerfectlySoft/PerfectLib.git
Updating https://github.com/PerfectlySoft/Perfect-COpenSSL.git
Cloning https://github.com/hkellaway/Gloss.git
Resolving https://github.com/hkellaway/Gloss.git at 2.0.0

Lowells-MacBook-Pro-2:PerfectTemplate lowellduke$ swift package generate-xcodeproj
'Gloss' /Users/lowellduke/Documents/PerfectTemplate/.build/checkouts/Gloss.git--9087498511083348710: error: package has unsupported layout; found loose source files: /Users/lowellduke/Documents/PerfectTemplate/.build/checkouts/Gloss.git--9087498511083348710/Tests/Comparators.swift, /Users/lowellduke/Documents/PerfectTemplate/.build/checkouts/Gloss.git--9087498511083348710/Tests/DecoderTests.swift, /Users/lowellduke/Documents/PerfectTemplate/.build/checkouts/Gloss.git--9087498511083348710/Tests/EncoderTests.swift, /Users/lowellduke/Documents/PerfectTemplate/.build/checkouts/Gloss.git--9087498511083348710/Tests/FlowObjectCreationTests.swift, /Users/lowellduke/Documents/PerfectTemplate/.build/checkouts/Gloss.git--9087498511083348710/Tests/GlossTests.swift, /Users/lowellduke/Documents/PerfectTemplate/.build/checkouts/Gloss.git--9087498511083348710/Tests/KeyPathTests.swift, /Users/lowellduke/Documents/PerfectTemplate/.build/checkouts/Gloss.git--9087498511083348710/Tests/ObjectToJSONFlowTests.swift, /Users/lowellduke/Documents/PerfectTemplate/.build/checkouts/Gloss.git--9087498511083348710/Tests/OperatorTests.swift

**Comment by hkellaway** [comment]
im not currently familiar with Swift Package manage and how it works, so cannot provide a solution for this

**Comment by str11ngfello** [comment]
Thanks for the response.  I found a workaround.  Your Test folder causes that command to fail. Apparently it doesn't like that layout. If I remove the test folder, Swift Package Manager works fine.

Cheers!

**Comment by hkellaway** [comment]
there must be a way to have tests in a project and not have Swift Package manager fail 🤔

**Comment by rbukovansky** [comment]
@str11ngfello @hkellaway Resolution of SPM issues will be part of Gloss on Linux solution I will be working soon...
