### ISSUE TITLE
Carthage update fails for macOS (umbrella header 'Gloss.h' not found). Shouldn't Glass MacOS target membership be "public"?

### ISSUE THREAD

**Issue by Abushawish** [hkellaway/Gloss#331]
Trying to do "carthage update --platform Mac" on my macOS app, but it's failing with the log stating:

```
...
Release/Gloss MacOS.build/unextended-module.modulemap:2:19: error: umbrella header 'Gloss.h' not found
  umbrella header "Gloss.h"
                  ^
<unknown>:0: error: could not build Objective-C module 'Gloss'
** ARCHIVE FAILED **
...
```

Looked into the Glass.h target membership, and noticed that it's "public" for "Gloss", but "project" for "Gloss MacOS". Should it be public for "Gloss MacOS" too?

Thanks!

Edit: Just noticed that the files being public is part of the code on Github, but not the latest release (2.0.0). Looks like I will need to use a specific branch/commit in carthage.

**Comment by hkellaway** [comment]
mistake on my part, i'll take a look

**Comment by hkellaway** [comment]
if you want to point to a specific branch at the moment, `release/2.0.1` has this fix; will be making an official `2.0.1` release some time today

**Comment by Abushawish** [comment]
Thank you!

**Comment by hkellaway** [comment]
welcome! 2.0.1 is out
