### ISSUE TITLE
Can't decode 'anonymous' values

### ISSUE THREAD

**Issue by AlexandreMinard** [hkellaway/Gloss#336]
Hi,

I don't know how to call this issue, sorry for that.

My problem is that I can't decode the struct 'MyTest' in my JSON model :

```
struct MyTest2: Glossy {
    let test2: String?
    
    init(json: JSON) {
        self.test2 = "test2" <~~ json
    }
    
    // MARK: - Serialization
    
    func toJSON() -> JSON? {
        return jsonify([
            "test2" ~~> self.test2,
            ])
    }
}

struct MyTest: Glossy {
    let test: [String : [String : MyTest2]]?
    init(json: JSON) {
        self.test = "test" <~~ json
    }
    
    func toJSON() -> JSON? {
        return jsonify([
            "test" ~~> self.test,
            ])
    }
}

```
Indeed, if I set the type of **MyTest.test** to **[String : [String : MyTest2]]?** decoding does not work.
But If I set the type of **MyTest.test** to **[String : [String : AnyObject]]?** decoding works fine but then I've to write this code to get my data:

```
for (key1,value1) in myJsonObject! {
    for (key2,value2) in value1 {
        let data = MyTest2(json: value2 as! JSON)
    }
}

```

That's something I don't want to do.

Any idea would be really really really appreciated.

Regards,
Alexandre

**Comment by hkellaway** [comment]
these are the types that Gloss handles automatically: 
https://github.com/hkellaway/Gloss#the-decode-operator-'

That doesn't include `[String :  [String : Decodable]]` (we could imagine tons of variants like this so Gloss has a minimum set of typical ones)

--

If you want to stay in the semantic pattern of Gloss, consider adding an `extension` to `Decoder` and `Encoder` that decodes/encodes that special value for you (and new `<~~` and `~~>` operation definitions even). 

^ but, that's not necessary - it would only to have your models be consistent in their usage of that operator

**Comment by AlexandreMinard** [comment]
Thanks for your answer.
Would you mind to give me a sample code for such `extension` please?

Regards,
Alexandre

**Comment by hkellaway** [comment]
this is psuedocode. i don't know if this will work, just a place to start trying:

```
extension Decoder {
	
	static func decode(customDictionaryForKey key: String, json: JSON) -> [String : [String : Decodable]]? {
		// logic to extract your type from json, nil if it fails
	}

}


func <~~ <T: JSONDecodable>(key: String, json: JSON) -> [String : Decodable]]? {
    return Decoder.decode(customDictionaryForKey: key, json: json)
}
```

**Comment by AlexandreMinard** [comment]
Thanks.
Look too hard for me right now :(
