### ISSUE TITLE
Cannot convert value of type 'JSON' to expected argument type 'JSON' (aka Dictionary<String, Any>')

### ISSUE THREAD

**Issue by george-gymamigo** [hkellaway/Gloss#337]
I'm using SwiftyJSON to handle JSON results however I get the error above.

` let QueriedJsonData = JSON(returnedJSON)
print(QueriedJsonData[0])
let currentUserJSONData = QueriedJsonData[0]
guard let currentUser = user(json: currentUserJSONData) else {
                 print("DECODING FAILURE :(")
                 return
}`

**Comment by hkellaway** [comment]
perhaps the type of currebtUserJSONData is not defined as the Gloss JSON type. it looks from that code like SwiftyJSON may also have its own JSON type so you’d have to specify:

try:
guard let currentUserJSONData = QueriedJsonData[0] as? Gloss.JSON

or
as? [String : Any]

as Gloss.JSON is just a typealias for [String : Any]
