### ISSUE TITLE
Unexpected E0F while looking for matching

### ISSUE THREAD

**Issue by george-gymamigo** [hkellaway/Gloss#339]
I get the following error after installing Gloss:
`PhaseScriptExecution [CP]\ Embed\ Pods\ Frameworks /Users/georgedendle/Library/Developer/Xcode/DerivedData/REEDSSC-ehlgmzzgrccyvbhcpfucoufqunar/Build/Intermediates.noindex/REEDSSC.build/Debug-iphonesimulator/REED\'S\ S&C.build/Script-F4EFDE5711B38ED5261C982E.sh
    cd "/Users/georgedendle/Dropbox/REED'S S&C"
    /bin/sh -c \"/Users/georgedendle/Library/Developer/Xcode/DerivedData/REEDSSC-ehlgmzzgrccyvbhcpfucoufqunar/Build/Intermediates.noindex/REEDSSC.build/Debug-iphonesimulator/REED\'S\ S&C.build/Script-F4EFDE5711B38ED5261C982E.sh\"

mkdir -p /Users/georgedendle/Library/Developer/Xcode/DerivedData/REEDSSC-ehlgmzzgrccyvbhcpfucoufqunar/Build/Products/Debug-iphonesimulator/REED'S S&C.app/Frameworks
rsync --delete -av --filter P .*.?????? --filter "- CVS/" --filter "- .svn/" --filter "- .git/" --filter "- .hg/" --filter "- Headers" --filter "- PrivateHeaders" --filter "- Modules" "/Users/georgedendle/Library/Developer/Xcode/DerivedData/REEDSSC-ehlgmzzgrccyvbhcpfucoufqunar/Build/Products/Debug-iphonesimulator/Gloss/Gloss.framework" "/Users/georgedendle/Library/Developer/Xcode/DerivedData/REEDSSC-ehlgmzzgrccyvbhcpfucoufqunar/Build/Products/Debug-iphonesimulator/REED'S S&C.app/Frameworks"
building file list ... done
Gloss.framework/
Gloss.framework/Gloss
Gloss.framework/Info.plist

sent 309983 bytes  received 70 bytes  620106.00 bytes/sec
total size is 309714  speedup is 1.00
Code Signing /Users/georgedendle/Library/Developer/Xcode/DerivedData/REEDSSC-ehlgmzzgrccyvbhcpfucoufqunar/Build/Products/Debug-iphonesimulator/REED'S S&C.app/Frameworks/Gloss.framework with Identity -
/usr/bin/codesign --force --sign -  --preserve-metadata=identifier,entitlements '/Users/georgedendle/Library/Developer/Xcode/DerivedData/REEDSSC-ehlgmzzgrccyvbhcpfucoufqunar/Build/Products/Debug-iphonesimulator/REED'S S&C.app/Frameworks/Gloss.framework'
/Users/georgedendle/Dropbox/REED'S S&C/Pods/Target Support Files/Pods-REED'S S&C/Pods-REED'S S&C-frameworks.sh: eval: line 113: unexpected EOF while looking for matching `''
Command /bin/sh failed with exit code 2`

**Comment by hkellaway** [comment]
that doesn’t indicate a problem with Gloss, rather perhaps CocoaPods or Xcode configuration.

**Comment by george-gymamigo** [comment]
How would you fix this? As it isn't appearing for my other pods installed
