### ISSUE TITLE
Value found for key "exclude_list" but decoding failed

### ISSUE THREAD

**Issue by Surya092** [hkellaway/Gloss#340]
JSON

"exclude_list" : [[{"variation_id":"3","group_id":"1"},{"variation_id":"10","group_id":"2"}],[{"variation_id":"10","group_id":"2"},{"variation_id":"22","group_id":"3"}]]}}

My Codes

struct Variants: JSONDecodable {
    var excludeList: [[ExcludeItem]]?
    init?(json: JSON) {
        self.excludeList = "exclude_list" <~~ json
    }
}

struct ExcludeItem: JSONDecodable {
    
    var variationId: String?
    var groupId: String?
    
    init?(json: JSON) {
        self.variationId = "variation_id" <~~ json
        self.groupId = "group_id" <~~ json
    }
    
}

The same works if I choose to use data type for exclude list as [[Any]]? instead of [[ExcludeItem]]?

**Comment by hkellaway** [comment]
Gloss has a finite amount of types it handles automatically (https://github.com/hkellaway/Gloss#the-decode-operator-) - arrays of arrays of Decodable is not one of them. you’ll have to create your own decoding logic for that
