### ISSUE TITLE
Initializer 'init()' is internal and cannot be referenced from a default argument value

### ISSUE THREAD

**Issue by johnflightsteter** [hkellaway/Gloss#341]
In a Swift 4.2 project using 

In ExtensionArray.swift

`static func from(data: Data, serializer: JSONSerializer = GlossJSONSerializer(),`

triggers error:

> Initializer 'init()' is internal and cannot be referenced from a default argument value

**Comment by hkellaway** [comment]
good catch ! i've fixed that. you can point to `develop` or commit `5f848a0db7c0b89e128e0a75d2b5b7b5e78525b3` until the next release
