### ISSUE TITLE
BaseResponse with Arrays and Generics

### ISSUE THREAD

**Issue by rtokun** [hkellaway/Gloss#343]
Lets say we have a base response, that using generics, similar to this:
```
struct BaseResponse<T: JSONDecodable> : JSONDecodable {
  
  let data: T?
  
  init?(json: JSON) {
    self.data = "data" <~~ json
  }
}
```

When the T is an Object everything works well, but if the T is an Array of Objects, the parsing from JSON, returns nil.
I ended up with creating 2 base responses, one as above and another one for Arrays as follows:
```
struct BaseArrayResponse<T: JSONDecodable> : JSONDecodable {

  let data: [T]?

  init?(json: JSON) {
    self.data = "data" <~~ json
  }
}
```
But it looks like should be a better solution for that, or maybe I am missing something.
Please advise

Thanks

**Comment by hkellaway** [comment]
no you're not missing something!

what i'd actually advise - it sounds from the types you're writing that you may be close the start of a project, it might be better to utilize the first-class `Codable` framework instead of relying heavily on a third-party.
