### ISSUE TITLE
Update to use Swift 4.2

### ISSUE THREAD

**Issue by yusuftor** [hkellaway/Gloss#344]
Please update the code to use Swift 4.2. This is the only framework I'm using now that hasn't upgraded to the latest version of Swift. Thanks!

**Comment by hkellaway** [comment]
good call - will update & release 2.1.0. stay tuned

**Comment by hkellaway** [comment]
as of right now, you can point to `develop` or commit `f9dfa86476a5f9e2ffeb777dfb3f98f52a23e16f` for Swift 4.2

still working on releasing to CocoaPods, having issues pushing the updated podspec

**Comment by hkellaway** [comment]
released - find in version 2.1.0 🎉
