### ISSUE TITLE
using guard while decoding object = Value found for key "topStory" but decoding failed.

### ISSUE THREAD

**Issue by JacquesCobi** [hkellaway/Gloss#349]
Not sure if there is something dumb that im missing, but it seems using a guard statement can affect how decoding an object goes.

for example, in my code when i go

```
    required init?(json: JSON) {
        
        guard let notWorking: NewsItem? = "topStory" <~~ json else {
            print("Didnt work")
            return nil
        }
    }
```

this will hit the return statement inside the guard statement with error "[Gloss] Value found for key "topStory" but decoding failed." 

but if i do this

```
    required init?(json: JSON) {

        let topStory: NewsItem? = "topStory" <~~ json 

        if topStory == nil {
            return nil
        }
    }
```
this will be fine and not hit the return statement, but ultimately should be the same thing?

So im not sure if there is some slight difference im not picking up, or if there is a bug of some kind, but this is what ive found. Ive attached a file below with my test data and test objects. Just call Test.test() in a sample project and it should demonstrate the issue.

[test.swift.zip](https://github.com/hkellaway/Gloss/files/2952453/test.swift.zip)

**Comment by hkellaway** [comment]
looking into it

**Comment by hkellaway** [comment]
so instead of `guard let topStory: NewsItem? = "topStory" <~~ json` use the following:

`guard let topStory: NewsItem? = "topStory" <~~ json`

i.e. its `NewsItem` not `NewsItem?`

its displaying that error because its looking for non-optional `NewsItem` not `NewsItem?`

**Comment by JacquesCobi** [comment]
Ah interesting, would have thought both non-optional and optional would be effectively equivalent. I've used guards with optionals in a lot of other places fine, but I guess non-optional is the correct way to go.

Thanks
