### ISSUE TITLE
swift5

### ISSUE THREAD

**Issue by frozen5555** [hkellaway/Gloss#350]
I love gloss very much, so please update it to swift5, thanks!

**Comment by hkellaway** [comment]
thank you! Gloss will definitely be updated to Swift 5 in due time

anyone who wants to get a headstart on this issue, i've created a branch called `swift5`. it has yet to be updated to be compatible as of this comment - but updates to achieve compatibility should be made against that branch

**Comment by frozen5555** [comment]
> thank you! Gloss will definitely be updated to Swift 5 in due time
> 
> anyone who wants to get a headstart on this issue, i've created a branch called `swift5`. it has yet to be updated to be compatible as of this comment - but updates to achieve compatibility should be made against that branch

ok，thanks！

**Comment by VivintMan** [comment]
I need the WatchOS target moved up to at least Swift 4, too.  Is that a thing you can do?  I just tried by cloning the repo, creating a branch called `swift5_watchOS`, but can't write to the repo, so got rejected.

**Comment by hkellaway** [comment]
@VivintMan you are correct - oversight on my part; i'm going to update `develop` with Swift 4 for the watchOS target; will track that in a separate issue
https://github.com/hkellaway/Gloss/issues/351

**Comment by VivintMan** [comment]
Excellent, thanks!

**Comment by hkellaway** [comment]
the project has been updated to Swift 5 - found on the `swift5` branch currently

**Comment by yusuftor** [comment]
Can we merge this yet?

**Comment by hkellaway** [comment]
thanks for the poke! slipped my mind

Gloss 3.0.0 has been release 🎉 Swift 5 compatibility
