### ISSUE TITLE
WatchOS target should be Swift 4

### ISSUE THREAD

**Issue by hkellaway** [hkellaway/Gloss#351]

**Comment by VivintMan** [comment]
Perfect, thanks!

**Comment by hkellaway** [comment]
@VivintMan to answer your question about releasing a version with this update - i dont have a specific cadence. i'd intend to include this in the `3.0.0` release along with the Swift 5 updates, unless theres a need for you to pin to a specific version

**Comment by hkellaway** [comment]
im gonna amend that on second thought - i'll make a `2.1.1` release for this issue

**Comment by VivintMan** [comment]
That's fantastic.  Thank you!

**Comment by hkellaway** [comment]
2.1.1 has been release ✨

**Comment by VivintMan** [comment]
🎉
Thanks again!
