### ISSUE TITLE
How to parse json that contains only array

### ISSUE THREAD

**Issue by scoobydoobeedoobeedoo** [hkellaway/Gloss#360]
Hi! 
I am having problem with parsing json object like {[...,...]} which contains only array. Constructor init?(json: JSON) is not firing at all.

**Comment by hkellaway** [comment]
there’s different syntax for creating models from JSON arrays

check out: https://github.com/hkellaway/Gloss#model-objects-from-json-arrays

**Comment by scoobydoobeedoobeedoo** [comment]
> there’s different syntax for creating models from JSON arrays
> 
> check out: https://github.com/hkellaway/Gloss#model-objects-from-json-arrays

oh, i'm sorry. Overlooked that.
