### ISSUE TITLE
The ISO 8601 date tests fail when ran in different time zones

### ISSUE THREAD

**Issue by bojan** [hkellaway/Gloss#55]
When running the tests on time zones different than the one the test was written, they fail when parsing the hour.

For example, in `testDecodeDateISO8601` in `DecoderTests.swift`, the object's hour is 21 UTC, the tests check for 17, but when running in continental Europe the test fails since the hour is translated into 23 CEST.

**Comment by hkellaway** [comment]
Nice catch

**Comment by hkellaway** [comment]
Resolved in PR https://github.com/hkellaway/Gloss/pull/57
