### ISSUE TITLE
Class Clusters

### ISSUE THREAD

**Issue by fabb** [hkellaway/Gloss#56]
Is support for class clusters planned?

I'm aware that Gloss is favorably used with structs. Though we have a use case where the server has a class hierarchy of DTOs, and the specific subclass can be derived from one property.

At the moment we use Mantle, but we investigate into other lightweight modeling frameworks that can also take advantage of Swift structs.

In this specific use case, we thought about just squashing all the subclasses' properties into one struct, but that just gets overcrowded, and in the code it's not obvious anymore which property sets belong to each other and need to be filled together - also when serializing to json, it's not allowed to send properties not present in the according original subclasses' serverside DTO.

Other suggestions than class clusters are welcome too!

**Comment by hkellaway** [comment]
there isn't a plan right now to go towards a class cluster/factory design.

i don't know if this helps you, but you _can_ represent your Gloss models as `class`es instead of `struct`s. what was originally this:

```
import Gloss

struct RepoOwner: Decodable {
    
    let ownerId: Int?
    let username: String?
    
    // MARK: - Deserialization
    
    init?(json: JSON) {
        self.ownerId = "id" <~~ json
        self.username = "login" <~~ json
    }
}
```

would become

```
import Gloss

class RepoOwner: Decodable {
    
    let ownerId: Int?
    let username: String?
    
    // MARK: - Deserialization
    
    required init?(json: JSON) {
        self.ownerId = "id" <~~ json
        self.username = "login" <~~ json
    }
}
```
