### ISSUE TITLE
Mac OS X support?

### ISSUE THREAD

**Issue by CodeEagle** [hkellaway/Gloss#75]
Mac OS X support?

**Comment by hkellaway** [comment]
Mac OS X is not my forte - so I'm not sure what it needs to take it there. If you have any thoughts on that, please share

**Comment by CodeEagle** [comment]
It's just work on Mac OS X.
Just copy and paste in a Cocoa Framework
Support Mac OS X just like iOS!!

![image](https://cloud.githubusercontent.com/assets/2311352/10714192/e2ec4724-7b1c-11e5-8477-b78612acfc0b.png)

![image](https://cloud.githubusercontent.com/assets/2311352/10714191/d9af8702-7b1c-11e5-90a4-03c09be4c663.png)

**Comment by hkellaway** [comment]
thanks for the tip - support added as of version `0.6.0` :tada:
