### ISSUE TITLE
Implementing Gloss protocol requires a class to be declared final

### ISSUE THREAD

**Issue by ishaq** [hkellaway/Gloss#83]
this takes away any possibility of inheritance for similar classes e.g. `Product` and `ProductDetail`. 

Since `Product` will have to be declared `final`, `ProductDetail` would end up replicating all the fields of `Product`.

I have no idea on how to fix it, or if it is even possible. I couldn't find a similar ticket in the closed issues so putting it on the radar. 

@hkellaway your thoughts please.

**Comment by CodeEagle** [comment]
`final` is marked can not be subclassing, is that right?

**Comment by ishaq** [comment]
yes.

**Comment by CodeEagle** [comment]
`final` is marked can not be subclassing, is that right?

**Comment by CodeEagle** [comment]
`ProductDetail ` subclassing `Product ` ?

**Comment by ishaq** [comment]
no. because `Product` is `final`

**Comment by CodeEagle** [comment]
Could you paste your code here?

**Comment by ishaq** [comment]
@CodeEagle what are you getting at if I may ask?

**Comment by CodeEagle** [comment]
not that clear, sorry buddy, thus I wanna take a look at it for sure

**Comment by ishaq** [comment]
1. Write a class that implements any of `Gloss` protocols (these are `Glossy`, `Decodable` and `Encodable`).
2. The compiler will tell you that you need to mark the class `final`.

Does it help?

**Comment by CodeEagle** [comment]
got it

**Comment by hkellaway** [comment]
sorry guys, haven't figure this one out quite yet

**Comment by bachino90** [comment]
This is my solution to this issue: https://github.com/hkellaway/Gloss/pull/103

**Comment by hkellaway** [comment]
will be addressed with `0.7.0` - thanks @bachino90!
