### ISSUE TITLE
Make Encodable extend CustomStringConvertible

### ISSUE THREAD

**Issue by milancermak** [hkellaway/Gloss#90]
In all of the Gloss models I have I found myself doing this:

```swift
var description: String {
    return toJSON()!.description
}
```

Have you considered making `Encodable` inherit the `CustomStringConvertible` protocol and provide a default implementation for `description` similar to the one above?

**Comment by hkellaway** [comment]
will look into this @milancermak - thanks for the suggestion

**Comment by hkellaway** [comment]
sorry it took me a couple days to come around. gave this a try and only received obscure errors. if you find a way to include this one, i'd encourage you to submit a PR!
