### ISSUE TITLE
The watchOS platform

### ISSUE THREAD

**Issue by micpringle** [hkellaway/Gloss#91]
Hello!

Is there any reason why `watchos` isn't listed as a supported platform in **Gloss.podspec**?

If not, could the podspec be updated with the following:

```
s.platforms = { :ios => "8.0", :osx => "10.9", :tvos => "9.0", :watchos => "2.0" }
```

Happy to fork and submit a P.R. if you'd prefer.

Thanks!

**Comment by hkellaway** [comment]
no particular reason, except I've not worked with watchOS yet in any capacity enough to tell me if simply adding that to the podspec will allow watchOS developers to use the library without any hitches. is that something you can verify? let me know - if it's all good, I'll make the PR if you haven't yet

**Comment by hkellaway** [comment]
did my best to address in PR #93 - thanks for the suggestion!

**Comment by micpringle** [comment]
Great, thanks!

Apologies for not responding sooner, but it's just been crazy lately.
