### ISSUE TITLE
Int64 fails to decode

### ISSUE THREAD

**Issue by op** [hkellaway/Gloss#97]
Sorry, I'm a complete newbie here. Seems like only `NSNumber` or `Int` works properly. If I use `Int64`, the cast in `Decoder.decode` fails. This is the workaround I used;

```swift
func decodeInt64(key: String) -> JSON -> Int64? {
    return {
        json in
        
        if let number = json[key] as? NSNumber {
            return number.longLongValue
        }
        
        return nil
    }
}
```

**Comment by hkellaway** [comment]
you've got that snippet correct. large numbers in JSON are `NSNumbers` (http://stackoverflow.com/questions/25974779/convert-json-anyobject-to-int64) - if you want an `Int64` of it, you'll have to make your own decode function

**Comment by hkellaway** [comment]
Release `0.7.3` adds decoding for `Int64` 🎉

**Comment by op** [comment]
Amazing. Thank you! :dancer:
