### ISSUE TITLE
How to deserialise native type arrays

### ISSUE THREAD

**Issue by Duffycola** [hkellaway/Gloss#99]
Hi, I'm new to Gloss and I struggle deserialising native object arrays.

For example I want to deserialise this object

```
{
   name: "Duffycola",
   values: [1,2,3,4,5]
}
```

I don't see how I would correctly extend Int to conform to the Decodable protocol, because the individual object "1" has no "key" and no enclosing brackets in the json. I think the problem is the fact that Decoder.decode() requires a key. Would it be possible to add a Decoder.decode method which simply casts the given string to Int?

````
extension Int : Decodable
{
	public init?(json: JSON) {
		guard let value : Int = "" <~~ json
		else { return nil }
		self.init(value)
	}
}
````

Second, the documentation gives as an example how to deserialise a collection of objects, meaning the array starts at the root. In this example, however, the array is a subpath. I thought of doing something like this, but I'm not sure:

`guard let durations: [Int] = Int.modelsFromJSONArray(("values" <~~ json)!)`

**Comment by RahulKatariya** [comment]
You don't have to extend Int to conform to Decodable. It will just work. Below is the code for model for that json.

    struct Dummy: Decodable {
        
        var name: String
        var values: [Int]?
        
        init?(json: JSON) {
            guard let id: String = "id" <~~ json else { return nil }
            
            self.id = id
            self.values = "values" <~~ json
        }
        
    }

**Comment by hkellaway** [comment]
thanks @RahulKatariya !
